// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package licensemanager

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-provider-awscc/internal/generic"
	"github.com/hashicorp/terraform-provider-awscc/internal/registry"
)

func schemaAttribute1e02acd741d61c8d2476608a() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Arn of the grant.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute1e5e569c700e7722cee9ea63() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "License Arn for the grant.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute2b34817d5b59ce359343fe18() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The key name of the tag.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute57b0afe354f83d820f729027() schema.Attribute {
	return (schema.ListAttribute{ /*START ATTRIBUTE*/
		ElementType: types.StringType,
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute5cbe5acbed78a5b0fd887365() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Name for the created Grant.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute711431fa185d7f2490e7c3b0() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute766bb3ad1f7a6c43e8a60c95() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The version of the grant.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute91ad5a77ce273b4ed8fa1680() schema.Attribute {
	return (schema.ListNestedAttribute{ /*START ATTRIBUTE*/
		NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Key
				"key": schemaAttribute2b34817d5b59ce359343fe18(),
				// Property: Value
				"value": schemaAttributee597c09d54b778475f2fcb40(),
			}, /*END SCHEMA*/
		}, /*END NESTED OBJECT*/
		Description: "A list of tags to attach.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributed1f751e8cb54dcc117f24fef() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Home region for the created grant.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributee597c09d54b778475f2fcb40() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The value for the tag.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func init() {
	registry.AddDataSourceFactory("awscc_licensemanager_grant", grantDataSource)
}

// grantDataSource returns the Terraform awscc_licensemanager_grant data source.
// This Terraform data source corresponds to the CloudFormation AWS::LicenseManager::Grant resource.
func grantDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AllowedOperations
		// CloudFormation resource type schema:
		//
		//	{
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"allowed_operations": schemaAttribute57b0afe354f83d820f729027(),
		// Property: GrantArn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Arn of the grant.",
		//	  "maxLength": 2048,
		//	  "type": "string"
		//	}
		"grant_arn": schemaAttribute1e02acd741d61c8d2476608a(),
		// Property: GrantName
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Name for the created Grant.",
		//	  "type": "string"
		//	}
		"grant_name": schemaAttribute5cbe5acbed78a5b0fd887365(),
		// Property: HomeRegion
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Home region for the created grant.",
		//	  "type": "string"
		//	}
		"home_region": schemaAttributed1f751e8cb54dcc117f24fef(),
		// Property: LicenseArn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "License Arn for the grant.",
		//	  "maxLength": 2048,
		//	  "type": "string"
		//	}
		"license_arn": schemaAttribute1e5e569c700e7722cee9ea63(),
		// Property: Principals
		// CloudFormation resource type schema:
		//
		//	{
		//	  "items": {
		//	    "maxLength": 2048,
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"principals": schemaAttribute57b0afe354f83d820f729027(),
		// Property: Status
		// CloudFormation resource type schema:
		//
		//	{
		//	  "type": "string"
		//	}
		"status": schemaAttribute711431fa185d7f2490e7c3b0(),
		// Property: Tags
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "A list of tags to attach.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "additionalProperties": false,
		//	    "description": "A key-value pair to associate with a resource.",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "The key name of the tag.",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "The value for the tag.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key",
		//	      "Value"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": false
		//	}
		"tags": schemaAttribute91ad5a77ce273b4ed8fa1680(),
		// Property: Version
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The version of the grant.",
		//	  "type": "string"
		//	}
		"version": schemaAttribute766bb3ad1f7a6c43e8a60c95(),
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for AWS::LicenseManager::Grant",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudFormationTypeName("AWS::LicenseManager::Grant").WithTerraformTypeName("awscc_licensemanager_grant")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"allowed_operations": "AllowedOperations",
		"grant_arn":          "GrantArn",
		"grant_name":         "GrantName",
		"home_region":        "HomeRegion",
		"key":                "Key",
		"license_arn":        "LicenseArn",
		"principals":         "Principals",
		"status":             "Status",
		"tags":               "Tags",
		"value":              "Value",
		"version":            "Version",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
