# Copyright IBM Corp. 2021, 2025
# "SPDX-License-Identifier: MPL-2.0"

# Terraform AWSCC Provider Copyplop Configuration
copyright:
  holder: "IBM Corp."
  start_year: 2021
  current_year: 2025
  format: "Copyright {{.Holder}} {{.StartYear}}, {{.CurrentYear}}"

license:
  enabled: true
  identifier: "MPL-2.0"
  format: "SPDX-License-Identifier: {{.Identifier}}"

# see breakdown of file types below
files:
  exclude_paths:
    - "**/when_string_test.go" # standard library generated files
    - "CHANGELOG.md"
    - "infrastructure/**"
    - "**/import_examples_gen.json"
    - "docs/**"
    - ".github/**"
    - "contributing/**"
    - "**/README.md"
    - "META.d/**"
    - ".semgrep/**"
  extensions:
    - ".go"
    - ".yml"
    - ".yaml"
    - ".md"

  comment_styles:
    go: "//"
    sh: "#"
    py: "#"
    hcl: "#"
    tf: "#"
    yml: "#"
    yaml: "#"
    md: "<!--"
    html_markdown: "<!--"

  below_frontmatter:
    - ".md"
    - ".html.markdown"

detection:
  skip_generated: false
  generated_patterns:
    - "Code generated"
    - "DO NOT EDIT"

  replace_patterns:
    - "Copyright.*HashiCorp"
    - "Copyright \\(c\\).*HashiCorp"
  max_scan_lines: 20

third_party:
  action: "above"
  patterns:
    - "Copyright.*[a-zA-Z0-9].*"