# Copyright IBM Corp. 2021, 2025
# "SPDX-License-Identifier: MPL-2.0"

version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - makezero
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/hashicorp/terraform-plugin-framework/tfsdk.State).SetAttribute
    gocritic:
      enabled-tags:
        - diagnostic
      disabled-tags:
        - style
        - performance
        - experimental
        - opinionated
    mnd:
      checks:
        - argument
        - assign
        - case
        - operation
        - return
      ignored-functions:
        - os.Exit
        - stringvalidator.LengthAtMost
        - stringvalidator.LengthBetween
    nolintlint:
      allow-unused: false
      allow-no-explanation:
        - mnd
    unparam:
      check-exported: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 10m
