# Configuration for markdownlint
# https://github.com/DavidAnson/markdownlint#configuration

default: true
MD007:
  indent: 4
MD010:
  code_blocks: false
MD046:
  style: fenced
MD048:
  style: backtick

# Disabled Rules

MD013: false # Line length: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013---line-length
MD014: false # Dollar signs before commands with no output: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md014---dollar-signs-used-before-commands-without-showing-output


