// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package codecommit

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-provider-awscc/internal/generic"
	"github.com/hashicorp/terraform-provider-awscc/internal/registry"
)

func schemaAttribute07e68eaa551a6edd5f2ff4db() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The name of the new repository to be created.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute0aa94e56010bb7616046cfc3() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The ID of the AWS Key Management Service encryption key used to encrypt and decrypt the repository.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute13c60e36960785bd358d9c64() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The tag's key.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute3d7d817db3bae9276b8ff1f5() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Optional. Specifies a branch name to be used as the default branch when importing code into a repository on initial creation. If this property is not set, the name main will be used for the default branch for the repository. Changes to this property are ignored after initial resource creation. We recommend using this parameter to set the name to main to align with the default behavior of CodeCommit unless another name is needed.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute47b4a5da3885c522cac1c1c1() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Any custom data associated with the trigger to be included in the information sent to the target of the trigger.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute5c1c809512e3fbe3c31c7ced() schema.Attribute {
	return (schema.ListAttribute{ /*START ATTRIBUTE*/
		ElementType: types.StringType,
		Description: "The repository events that cause the trigger to run actions in another service, such as sending a notification through Amazon SNS.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute642b34802b0e8e35e589e4c3() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The repository's name.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute6e67f85969138da38c7d2f25() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The ARN of the resource that is the target for a trigger (for example, the ARN of a topic in Amazon SNS).",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute748bec765090e62bf5c5ce68() schema.Attribute {
	return (schema.ListNestedAttribute{ /*START ATTRIBUTE*/
		NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Branches
				"branches": schemaAttribute8bb86daeeeb596d22395d740(),
				// Property: CustomData
				"custom_data": schemaAttribute47b4a5da3885c522cac1c1c1(),
				// Property: DestinationArn
				"destination_arn": schemaAttribute6e67f85969138da38c7d2f25(),
				// Property: Events
				"events": schemaAttribute5c1c809512e3fbe3c31c7ced(),
				// Property: Name
				"name": schemaAttributeb7461005f89fd6f410bd20fa(),
			}, /*END SCHEMA*/
		}, /*END NESTED OBJECT*/
		Description: "Information about a trigger for a repository.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute7e0abcacc9cf4a0de35dffea() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The Amazon Resource Name (ARN) of the repository.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute8728d9e791d2f26cf3fe88ef() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "A comment or description about the new repository.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute8af36bdfa1a9d60feeddee40() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The URL to use for cloning the repository over HTTPS.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute8bb86daeeeb596d22395d740() schema.Attribute {
	return (schema.ListAttribute{ /*START ATTRIBUTE*/
		ElementType: types.StringType,
		Description: "The branches to be included in the trigger configuration. If you specify an empty array, the trigger applies to all branches.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute8c715f37447592b56b995db5() schema.Attribute {
	return (schema.ListNestedAttribute{ /*START ATTRIBUTE*/
		NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Key
				"key": schemaAttribute13c60e36960785bd358d9c64(),
				// Property: Value
				"value": schemaAttributea3de90a30b0faf75ee331e27(),
			}, /*END SCHEMA*/
		}, /*END NESTED OBJECT*/
		Description: "One or more tag key-value pairs to use when tagging this repository.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute90c4e331f92cfd00c2a4cd4c() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The key to use for accessing the Amazon S3 bucket. Changes to this property are ignored after initial resource creation.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributea10d26cdebf9d660e4e9cd2b() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: BranchName
			"branch_name": schemaAttribute3d7d817db3bae9276b8ff1f5(),
			// Property: S3
			"s3": schemaAttributebd5c498d53d89c526621b624(),
		}, /*END SCHEMA*/
		Description: "Information about code to be committed to a repository after it is created in an AWS CloudFormation stack. Information about code is only used in resource creation. Updates to a stack will not reflect changes made to code properties after initial resource creation.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributea3de90a30b0faf75ee331e27() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The tag's value.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributea86851b536cf4820be4bc0ef() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The ID of the repository.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributeb7461005f89fd6f410bd20fa() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The name of the trigger.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributeb76152df3a23cc6c1d83d898() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The object version of the ZIP file, if versioning is enabled for the Amazon S3 bucket. Changes to this property are ignored after initial resource creation.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributebd5c498d53d89c526621b624() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Bucket
			"bucket": schemaAttributee5a66cb6a486448762ee062d(),
			// Property: Key
			"key": schemaAttribute90c4e331f92cfd00c2a4cd4c(),
			// Property: ObjectVersion
			"object_version": schemaAttributeb76152df3a23cc6c1d83d898(),
		}, /*END SCHEMA*/
		Description: "Information about the Amazon S3 bucket that contains a ZIP file of code to be committed to the repository. Changes to this property are ignored after initial resource creation.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributeceef342a87b8dd5aa7b98c34() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The URL to use for cloning the repository over SSH.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributee5a66cb6a486448762ee062d() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The name of the Amazon S3 bucket that contains the ZIP file with the content that will be committed to the new repository. This can be specified using the name of the bucket in the AWS account. Changes to this property are ignored after initial resource creation.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func init() {
	registry.AddDataSourceFactory("awscc_codecommit_repository", repositoryDataSource)
}

// repositoryDataSource returns the Terraform awscc_codecommit_repository data source.
// This Terraform data source corresponds to the CloudFormation AWS::CodeCommit::Repository resource.
func repositoryDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: Arn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The Amazon Resource Name (ARN) of the repository.",
		//	  "type": "string"
		//	}
		"arn": schemaAttribute7e0abcacc9cf4a0de35dffea(),
		// Property: CloneUrlHttp
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The URL to use for cloning the repository over HTTPS.",
		//	  "type": "string"
		//	}
		"clone_url_http": schemaAttribute8af36bdfa1a9d60feeddee40(),
		// Property: CloneUrlSsh
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The URL to use for cloning the repository over SSH.",
		//	  "type": "string"
		//	}
		"clone_url_ssh": schemaAttributeceef342a87b8dd5aa7b98c34(),
		// Property: Code
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "description": "Information about code to be committed to a repository after it is created in an AWS CloudFormation stack. Information about code is only used in resource creation. Updates to a stack will not reflect changes made to code properties after initial resource creation.",
		//	  "properties": {
		//	    "BranchName": {
		//	      "description": "Optional. Specifies a branch name to be used as the default branch when importing code into a repository on initial creation. If this property is not set, the name main will be used for the default branch for the repository. Changes to this property are ignored after initial resource creation. We recommend using this parameter to set the name to main to align with the default behavior of CodeCommit unless another name is needed.",
		//	      "maxLength": 256,
		//	      "minLength": 1,
		//	      "type": "string"
		//	    },
		//	    "S3": {
		//	      "additionalProperties": false,
		//	      "description": "Information about the Amazon S3 bucket that contains a ZIP file of code to be committed to the repository. Changes to this property are ignored after initial resource creation.",
		//	      "properties": {
		//	        "Bucket": {
		//	          "description": "The name of the Amazon S3 bucket that contains the ZIP file with the content that will be committed to the new repository. This can be specified using the name of the bucket in the AWS account. Changes to this property are ignored after initial resource creation.",
		//	          "maxLength": 63,
		//	          "minLength": 3,
		//	          "type": "string"
		//	        },
		//	        "Key": {
		//	          "description": "The key to use for accessing the Amazon S3 bucket. Changes to this property are ignored after initial resource creation.",
		//	          "maxLength": 1024,
		//	          "minLength": 1,
		//	          "type": "string"
		//	        },
		//	        "ObjectVersion": {
		//	          "description": "The object version of the ZIP file, if versioning is enabled for the Amazon S3 bucket. Changes to this property are ignored after initial resource creation.",
		//	          "maxLength": 1024,
		//	          "minLength": 1,
		//	          "type": "string"
		//	        }
		//	      },
		//	      "required": [
		//	        "Bucket",
		//	        "Key"
		//	      ],
		//	      "type": "object"
		//	    }
		//	  },
		//	  "required": [
		//	    "S3"
		//	  ],
		//	  "type": "object"
		//	}
		"code": schemaAttributea10d26cdebf9d660e4e9cd2b(),
		// Property: KmsKeyId
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The ID of the AWS Key Management Service encryption key used to encrypt and decrypt the repository.",
		//	  "maxLength": 100,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"kms_key_id": schemaAttribute0aa94e56010bb7616046cfc3(),
		// Property: Name
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The repository's name.",
		//	  "type": "string"
		//	}
		"name": schemaAttribute642b34802b0e8e35e589e4c3(),
		// Property: RepositoryDescription
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "A comment or description about the new repository.",
		//	  "maxLength": 1000,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"repository_description": schemaAttribute8728d9e791d2f26cf3fe88ef(),
		// Property: RepositoryId
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The ID of the repository.",
		//	  "type": "string"
		//	}
		"repository_id": schemaAttributea86851b536cf4820be4bc0ef(),
		// Property: RepositoryName
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The name of the new repository to be created.",
		//	  "maxLength": 100,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"repository_name": schemaAttribute07e68eaa551a6edd5f2ff4db(),
		// Property: Tags
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "One or more tag key-value pairs to use when tagging this repository.",
		//	  "items": {
		//	    "additionalProperties": false,
		//	    "description": "A tag is a key-value pair that is used to manage the resource.",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "The tag's key.",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "The tag's value.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Value",
		//	      "Key"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schemaAttribute8c715f37447592b56b995db5(),
		// Property: Triggers
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Information about a trigger for a repository.",
		//	  "items": {
		//	    "additionalProperties": false,
		//	    "description": "Information about a trigger for a repository.",
		//	    "properties": {
		//	      "Branches": {
		//	        "description": "The branches to be included in the trigger configuration. If you specify an empty array, the trigger applies to all branches.",
		//	        "items": {
		//	          "type": "string"
		//	        },
		//	        "type": "array",
		//	        "uniqueItems": false
		//	      },
		//	      "CustomData": {
		//	        "description": "Any custom data associated with the trigger to be included in the information sent to the target of the trigger.",
		//	        "type": "string"
		//	      },
		//	      "DestinationArn": {
		//	        "description": "The ARN of the resource that is the target for a trigger (for example, the ARN of a topic in Amazon SNS).",
		//	        "type": "string"
		//	      },
		//	      "Events": {
		//	        "description": "The repository events that cause the trigger to run actions in another service, such as sending a notification through Amazon SNS.",
		//	        "items": {
		//	          "type": "string"
		//	        },
		//	        "type": "array",
		//	        "uniqueItems": false
		//	      },
		//	      "Name": {
		//	        "description": "The name of the trigger.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Events",
		//	      "DestinationArn",
		//	      "Name"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": false
		//	}
		"triggers": schemaAttribute748bec765090e62bf5c5ce68(),
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for AWS::CodeCommit::Repository",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudFormationTypeName("AWS::CodeCommit::Repository").WithTerraformTypeName("awscc_codecommit_repository")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"arn":                    "Arn",
		"branch_name":            "BranchName",
		"branches":               "Branches",
		"bucket":                 "Bucket",
		"clone_url_http":         "CloneUrlHttp",
		"clone_url_ssh":          "CloneUrlSsh",
		"code":                   "Code",
		"custom_data":            "CustomData",
		"destination_arn":        "DestinationArn",
		"events":                 "Events",
		"key":                    "Key",
		"kms_key_id":             "KmsKeyId",
		"name":                   "Name",
		"object_version":         "ObjectVersion",
		"repository_description": "RepositoryDescription",
		"repository_id":          "RepositoryId",
		"repository_name":        "RepositoryName",
		"s3":                     "S3",
		"tags":                   "Tags",
		"triggers":               "Triggers",
		"value":                  "Value",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
