// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package wisdom

import (
	"context"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-provider-awscc/internal/generic"
	"github.com/hashicorp/terraform-provider-awscc/internal/identity"
	"github.com/hashicorp/terraform-provider-awscc/internal/registry"
)

func schemaAttribute1a62632ba1570d2f475a4790() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Computed: true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute718765711e344ec75c678aad() schema.Attribute {
	return (schema.Float64Attribute{ /*START ATTRIBUTE*/
		Optional: true,
		Computed: true,
		PlanModifiers: []planmodifier.Float64{ /*START PLAN MODIFIERS*/
			float64planmodifier.UseStateForUnknown(),
			float64planmodifier.RequiresReplaceIfConfigured(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute9375213791a16b410c90e49f() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Required: true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.RegexMatches(regexp.MustCompile("^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$"), ""),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.RequiresReplace(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributea3b963132fae7dde31b83ebe() schema.Attribute {
	return (schema.Float64Attribute{ /*START ATTRIBUTE*/
		Computed: true,
		PlanModifiers: []planmodifier.Float64{ /*START PLAN MODIFIERS*/
			float64planmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func init() {
	registry.AddResourceFactory("awscc_wisdom_ai_agent_version", aIAgentVersionResource)
}

// aIAgentVersionResource returns the Terraform awscc_wisdom_ai_agent_version resource.
// This Terraform resource corresponds to the CloudFormation AWS::Wisdom::AIAgentVersion resource.
func aIAgentVersionResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AIAgentArn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "pattern": "^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}){0,2}(:[A-Z0-9_$]+){0,1}$",
		//	  "type": "string"
		//	}
		"ai_agent_arn": schemaAttribute1a62632ba1570d2f475a4790(),
		// Property: AIAgentId
		// CloudFormation resource type schema:
		//
		//	{
		//	  "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$",
		//	  "type": "string"
		//	}
		"ai_agent_id": schemaAttribute9375213791a16b410c90e49f(),
		// Property: AIAgentVersionId
		// CloudFormation resource type schema:
		//
		//	{
		//	  "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(:[A-Z0-9_$]+){0,1}$",
		//	  "type": "string"
		//	}
		"ai_agent_version_id": schemaAttribute1a62632ba1570d2f475a4790(),
		// Property: AssistantArn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "pattern": "^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})?$",
		//	  "type": "string"
		//	}
		"assistant_arn": schemaAttribute1a62632ba1570d2f475a4790(),
		// Property: AssistantId
		// CloudFormation resource type schema:
		//
		//	{
		//	  "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$",
		//	  "type": "string"
		//	}
		"assistant_id": schemaAttribute9375213791a16b410c90e49f(),
		// Property: ModifiedTimeSeconds
		// CloudFormation resource type schema:
		//
		//	{
		//	  "type": "number"
		//	}
		"modified_time_seconds": schemaAttribute718765711e344ec75c678aad(),
		// Property: VersionNumber
		// CloudFormation resource type schema:
		//
		//	{
		//	  "type": "number"
		//	}
		"version_number": schemaAttributea3b963132fae7dde31b83ebe(),
	} /*END SCHEMA*/

	// Corresponds to CloudFormation primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Definition of AWS::Wisdom::AIAgentVersion Resource Type",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudFormationTypeName("AWS::Wisdom::AIAgentVersion").WithTerraformTypeName("awscc_wisdom_ai_agent_version")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithPrimaryIdentifier(
		identity.Identifier{
			Name:              "assistant_id",
			RequiredForImport: true,
		},
		identity.Identifier{
			Name:              "ai_agent_id",
			RequiredForImport: true,
		},
		identity.Identifier{
			Name:              "version_number",
			RequiredForImport: true,
		})

	opts = opts.WithAttributeNameMap(map[string]string{
		"ai_agent_arn":          "AIAgentArn",
		"ai_agent_id":           "AIAgentId",
		"ai_agent_version_id":   "AIAgentVersionId",
		"assistant_arn":         "AssistantArn",
		"assistant_id":          "AssistantId",
		"modified_time_seconds": "ModifiedTimeSeconds",
		"version_number":        "VersionNumber",
	})

	opts = opts.IsImmutableType(true)

	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
