// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package iotsitewise

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-provider-awscc/internal/generic"
	"github.com/hashicorp/terraform-provider-awscc/internal/identity"
	"github.com/hashicorp/terraform-provider-awscc/internal/registry"
	fwvalidators "github.com/hashicorp/terraform-provider-awscc/internal/validators"
)

func schemaAttribute08f3735432119ced5c08cf93() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Optional: true,
		Computed: true,
		Validators: []validator.String{ /*START VALIDATORS*/
			fwvalidators.NotNullString(),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute772273448e5774f2af848bf6() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "A description for the dashboard.",
		Required:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute7cb10b2898df73ffae5f9783() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The ID of the dashboard.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute96915e78f51e9881e69621a0() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The ID of the project in which to create the dashboard.",
		Optional:    true,
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
			stringplanmodifier.RequiresReplaceIfConfigured(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute9cf9f813712625a1ce5afdae() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The dashboard definition specified in a JSON literal.",
		Required:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributeb5dcc5abe1a502a877e90d10() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The ARN of the dashboard.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributeeef17ea808f3186a9723a4c7() schema.Attribute {
	return (schema.ListNestedAttribute{ /*START ATTRIBUTE*/
		NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Key
				"key": schemaAttribute08f3735432119ced5c08cf93(),
				// Property: Value
				"value": schemaAttribute08f3735432119ced5c08cf93(),
			}, /*END SCHEMA*/
		}, /*END NESTED OBJECT*/
		Description: "A list of key-value pairs that contain metadata for the dashboard.",
		Optional:    true,
		Computed:    true,
		PlanModifiers: []planmodifier.List{ /*START PLAN MODIFIERS*/
			generic.Multiset(),
			listplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributef5ae9ad6538ee7f80c7e48ce() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "A friendly name for the dashboard.",
		Required:    true,
	} /*END ATTRIBUTE*/)
}

func init() {
	registry.AddResourceFactory("awscc_iotsitewise_dashboard", dashboardResource)
	registry.AddListResourceFactory("awscc_iotsitewise_dashboard", generic.NewListResource(dashboardResource))
}

// dashboardResource returns the Terraform awscc_iotsitewise_dashboard resource.
// This Terraform resource corresponds to the CloudFormation AWS::IoTSiteWise::Dashboard resource.
func dashboardResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: DashboardArn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The ARN of the dashboard.",
		//	  "type": "string"
		//	}
		"dashboard_arn": schemaAttributeb5dcc5abe1a502a877e90d10(),
		// Property: DashboardDefinition
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The dashboard definition specified in a JSON literal.",
		//	  "type": "string"
		//	}
		"dashboard_definition": schemaAttribute9cf9f813712625a1ce5afdae(),
		// Property: DashboardDescription
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "A description for the dashboard.",
		//	  "type": "string"
		//	}
		"dashboard_description": schemaAttribute772273448e5774f2af848bf6(),
		// Property: DashboardId
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The ID of the dashboard.",
		//	  "type": "string"
		//	}
		"dashboard_id": schemaAttribute7cb10b2898df73ffae5f9783(),
		// Property: DashboardName
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "A friendly name for the dashboard.",
		//	  "type": "string"
		//	}
		"dashboard_name": schemaAttributef5ae9ad6538ee7f80c7e48ce(),
		// Property: ProjectId
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The ID of the project in which to create the dashboard.",
		//	  "type": "string"
		//	}
		"project_id": schemaAttribute96915e78f51e9881e69621a0(),
		// Property: Tags
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "A list of key-value pairs that contain metadata for the dashboard.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "additionalProperties": false,
		//	    "description": "To add or update tag, provide both key and value. To delete tag, provide only tag key to be deleted",
		//	    "properties": {
		//	      "Key": {
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key",
		//	      "Value"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": false
		//	}
		"tags": schemaAttributeeef17ea808f3186a9723a4c7(),
	} /*END SCHEMA*/

	// Corresponds to CloudFormation primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Resource schema for AWS::IoTSiteWise::Dashboard",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudFormationTypeName("AWS::IoTSiteWise::Dashboard").WithTerraformTypeName("awscc_iotsitewise_dashboard")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithPrimaryIdentifier(
		identity.Identifier{
			Name:              "dashboard_id",
			Description:       "The ID of the dashboard",
			RequiredForImport: true,
		})

	opts = opts.WithAttributeNameMap(map[string]string{
		"dashboard_arn":         "DashboardArn",
		"dashboard_definition":  "DashboardDefinition",
		"dashboard_description": "DashboardDescription",
		"dashboard_id":          "DashboardId",
		"dashboard_name":        "DashboardName",
		"key":                   "Key",
		"project_id":            "ProjectId",
		"tags":                  "Tags",
		"value":                 "Value",
	})

	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
