// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package resiliencehubv2

import (
	"context"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-provider-awscc/internal/generic"
	"github.com/hashicorp/terraform-provider-awscc/internal/identity"
	"github.com/hashicorp/terraform-provider-awscc/internal/registry"
)

func schemaAttribute0466c1680443fd811ad285ca() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		CustomType:  timetypes.RFC3339Type{},
		Description: "The timestamp when the service function was last updated.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute39571ca95c20ce493900df60() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The ARN of the parent service.",
		Required:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.RequiresReplace(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute4462d4e1a3d4509e28501f66() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The server-generated service function ID.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute756e82c54dc587e349b19cd5() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The description of the service function.",
		Optional:    true,
		Computed:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.LengthAtMost(500),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute8f1c778a0897e74a96584980() schema.Attribute {
	return (schema.Int64Attribute{ /*START ATTRIBUTE*/
		Description: "The number of resources associated with this function.",
		Computed:    true,
		PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
			int64planmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributea5a30d0957ca87d8c62d0f05() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The source of the service function.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributeb5b1e1800ee6c2a0bb509f0e() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		CustomType:  timetypes.RFC3339Type{},
		Description: "The timestamp when the service function was created.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributef2c9ae3ef557c439508d080a() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The criticality of the service function.",
		Required:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.OneOf(
				"PRIMARY",
				"SUPPLEMENTAL",
			),
		}, /*END VALIDATORS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributef91de1506565219a08649a5d() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The name of the service function.",
		Required:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.RegexMatches(regexp.MustCompile("^[A-Za-z0-9][A-Za-z0-9_\\-]{1,59}$"), ""),
		}, /*END VALIDATORS*/
	} /*END ATTRIBUTE*/)
}

func init() {
	registry.AddResourceFactory("awscc_resiliencehubv2_service_function", serviceFunctionResource)
}

// serviceFunctionResource returns the Terraform awscc_resiliencehubv2_service_function resource.
// This Terraform resource corresponds to the CloudFormation AWS::ResilienceHubV2::ServiceFunction resource.
func serviceFunctionResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: CreatedAt
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The timestamp when the service function was created.",
		//	  "format": "date-time",
		//	  "type": "string"
		//	}
		"created_at": schemaAttributeb5b1e1800ee6c2a0bb509f0e(),
		// Property: Criticality
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The criticality of the service function.",
		//	  "enum": [
		//	    "PRIMARY",
		//	    "SUPPLEMENTAL"
		//	  ],
		//	  "type": "string"
		//	}
		"criticality": schemaAttributef2c9ae3ef557c439508d080a(),
		// Property: Description
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The description of the service function.",
		//	  "maxLength": 500,
		//	  "type": "string"
		//	}
		"description": schemaAttribute756e82c54dc587e349b19cd5(),
		// Property: Name
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The name of the service function.",
		//	  "pattern": "^[A-Za-z0-9][A-Za-z0-9_\\-]{1,59}$",
		//	  "type": "string"
		//	}
		"name": schemaAttributef91de1506565219a08649a5d(),
		// Property: ResourceCount
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The number of resources associated with this function.",
		//	  "type": "integer"
		//	}
		"resource_count": schemaAttribute8f1c778a0897e74a96584980(),
		// Property: ServiceArn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The ARN of the parent service.",
		//	  "pattern": "",
		//	  "type": "string"
		//	}
		"service_arn": schemaAttribute39571ca95c20ce493900df60(),
		// Property: ServiceFunctionId
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The server-generated service function ID.",
		//	  "type": "string"
		//	}
		"service_function_id": schemaAttribute4462d4e1a3d4509e28501f66(),
		// Property: Source
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The source of the service function.",
		//	  "enum": [
		//	    "AI_GENERATED",
		//	    "USER"
		//	  ],
		//	  "type": "string"
		//	}
		"source": schemaAttributea5a30d0957ca87d8c62d0f05(),
		// Property: UpdatedAt
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The timestamp when the service function was last updated.",
		//	  "format": "date-time",
		//	  "type": "string"
		//	}
		"updated_at": schemaAttribute0466c1680443fd811ad285ca(),
	} /*END SCHEMA*/

	// Corresponds to CloudFormation primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Creates a service function within a Resilience Hub service.",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudFormationTypeName("AWS::ResilienceHubV2::ServiceFunction").WithTerraformTypeName("awscc_resiliencehubv2_service_function")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithPrimaryIdentifier(
		identity.Identifier{
			Name:              "service_arn",
			Description:       "The ARN of the parent service",
			RequiredForImport: true,
		},
		identity.Identifier{
			Name:              "service_function_id",
			Description:       "The server-generated service function ID",
			RequiredForImport: true,
		})

	opts = opts.WithAttributeNameMap(map[string]string{
		"created_at":          "CreatedAt",
		"criticality":         "Criticality",
		"description":         "Description",
		"name":                "Name",
		"resource_count":      "ResourceCount",
		"service_arn":         "ServiceArn",
		"service_function_id": "ServiceFunctionId",
		"source":              "Source",
		"updated_at":          "UpdatedAt",
	})

	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
