// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package cloudfront

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-provider-awscc/internal/generic"
	"github.com/hashicorp/terraform-provider-awscc/internal/identity"
	"github.com/hashicorp/terraform-provider-awscc/internal/registry"
	fwvalidators "github.com/hashicorp/terraform-provider-awscc/internal/validators"
)

func schemaAttribute15be7516f376bb7cf8130f6d() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		CustomType:  timetypes.RFC3339Type{},
		Description: "",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute1c941efd4db0bb8dc54f9e70() schema.Attribute {
	return (schema.BoolAttribute{ /*START ATTRIBUTE*/
		Description: "",
		Computed:    true,
		PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
			boolplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute48132ed0659bee2357e66765() schema.Attribute {
	return (schema.BoolAttribute{ /*START ATTRIBUTE*/
		Description: "IPv6 is enabled for the connection group.",
		Optional:    true,
		Computed:    true,
		PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
			boolplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute68ea0c91819f5fc7abf1c917() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "A string that contains an optional ``Tag`` value.\n The string length should be between 0 and 256 characters. Valid characters include ``a-z``, ``A-Z``, ``0-9``, space, and the special characters ``_ - . : / = + @``.",
		Optional:    true,
		Computed:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			fwvalidators.NotNullString(),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute6a28d13b3289cb9571d3ba46() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "A string that contains ``Tag`` key.\n The string length should be between 1 and 128 characters. Valid characters include ``a-z``, ``A-Z``, ``0-9``, space, and the special characters ``_ - . : / = + @``.",
		Optional:    true,
		Computed:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			fwvalidators.NotNullString(),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute6b816b6a3c11143d8fc46e63() schema.Attribute {
	return (schema.BoolAttribute{ /*START ATTRIBUTE*/
		Description: "Whether the connection group is enabled.",
		Optional:    true,
		Computed:    true,
		PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
			boolplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute847669fd3469e7b999a64ef2() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributea937aa4d49f11bcb26f600da() schema.Attribute {
	return (schema.ListNestedAttribute{ /*START ATTRIBUTE*/
		NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Key
				"key": schemaAttribute6a28d13b3289cb9571d3ba46(),
				// Property: Value
				"value": schemaAttribute68ea0c91819f5fc7abf1c917(),
			}, /*END SCHEMA*/
		}, /*END NESTED OBJECT*/
		Description: "A complex type that contains zero or more ``Tag`` elements.",
		Optional:    true,
		Computed:    true,
		PlanModifiers: []planmodifier.List{ /*START PLAN MODIFIERS*/
			listplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributebbd3f680fe7ade4b9ab23ae6() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The ID of the Anycast static IP list.",
		Optional:    true,
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributed8fa20c7b68a91a8dc36d404() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The name of the connection group.",
		Required:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.RequiresReplace(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func init() {
	registry.AddResourceFactory("awscc_cloudfront_connection_group", connectionGroupResource)
	registry.AddListResourceFactory("awscc_cloudfront_connection_group", generic.NewListResource(connectionGroupResource))
}

// connectionGroupResource returns the Terraform awscc_cloudfront_connection_group resource.
// This Terraform resource corresponds to the CloudFormation AWS::CloudFront::ConnectionGroup resource.
func connectionGroupResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AnycastIpListId
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The ID of the Anycast static IP list.",
		//	  "type": "string"
		//	}
		"anycast_ip_list_id": schemaAttributebbd3f680fe7ade4b9ab23ae6(),
		// Property: Arn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "",
		//	  "type": "string"
		//	}
		"arn": schemaAttribute847669fd3469e7b999a64ef2(),
		// Property: CreatedTime
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "",
		//	  "format": "date-time",
		//	  "type": "string"
		//	}
		"created_time": schemaAttribute15be7516f376bb7cf8130f6d(),
		// Property: ETag
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "",
		//	  "type": "string"
		//	}
		"e_tag": schemaAttribute847669fd3469e7b999a64ef2(),
		// Property: Enabled
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Whether the connection group is enabled.",
		//	  "type": "boolean"
		//	}
		"enabled": schemaAttribute6b816b6a3c11143d8fc46e63(),
		// Property: Id
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "",
		//	  "type": "string"
		//	}
		"connection_group_id": schemaAttribute847669fd3469e7b999a64ef2(),
		// Property: Ipv6Enabled
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "IPv6 is enabled for the connection group.",
		//	  "type": "boolean"
		//	}
		"ipv_6_enabled": schemaAttribute48132ed0659bee2357e66765(),
		// Property: IsDefault
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "",
		//	  "type": "boolean"
		//	}
		"is_default": schemaAttribute1c941efd4db0bb8dc54f9e70(),
		// Property: LastModifiedTime
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "",
		//	  "format": "date-time",
		//	  "type": "string"
		//	}
		"last_modified_time": schemaAttribute15be7516f376bb7cf8130f6d(),
		// Property: Name
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The name of the connection group.",
		//	  "type": "string"
		//	}
		"name": schemaAttributed8fa20c7b68a91a8dc36d404(),
		// Property: RoutingEndpoint
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "",
		//	  "type": "string"
		//	}
		"routing_endpoint": schemaAttribute847669fd3469e7b999a64ef2(),
		// Property: Status
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "",
		//	  "type": "string"
		//	}
		"status": schemaAttribute847669fd3469e7b999a64ef2(),
		// Property: Tags
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "A complex type that contains zero or more ``Tag`` elements.",
		//	  "items": {
		//	    "additionalProperties": false,
		//	    "description": "A complex type that contains ``Tag`` key and ``Tag`` value.",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "A string that contains ``Tag`` key.\n The string length should be between 1 and 128 characters. Valid characters include ``a-z``, ``A-Z``, ``0-9``, space, and the special characters ``_ - . : / = + @``.",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "A string that contains an optional ``Tag`` value.\n The string length should be between 0 and 256 characters. Valid characters include ``a-z``, ``A-Z``, ``0-9``, space, and the special characters ``_ - . : / = + @``.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Value",
		//	      "Key"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": false
		//	}
		"tags": schemaAttributea937aa4d49f11bcb26f600da(),
	} /*END SCHEMA*/

	// Corresponds to CloudFormation primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "The connection group for your distribution tenants. When you first create a distribution tenant and you don't specify a connection group, CloudFront will automatically create a default connection group for you. When you create a new distribution tenant and don't specify a connection group, the default one will be associated with your distribution tenant.",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudFormationTypeName("AWS::CloudFront::ConnectionGroup").WithTerraformTypeName("awscc_cloudfront_connection_group")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithPrimaryIdentifier(
		identity.Identifier{
			Name:              "id",
			RequiredForImport: true,
		})

	opts = opts.IsGlobalResourceType(true)
	opts = opts.WithAttributeNameMap(map[string]string{
		"anycast_ip_list_id":  "AnycastIpListId",
		"arn":                 "Arn",
		"connection_group_id": "Id",
		"created_time":        "CreatedTime",
		"e_tag":               "ETag",
		"enabled":             "Enabled",
		"ipv_6_enabled":       "Ipv6Enabled",
		"is_default":          "IsDefault",
		"key":                 "Key",
		"last_modified_time":  "LastModifiedTime",
		"name":                "Name",
		"routing_endpoint":    "RoutingEndpoint",
		"status":              "Status",
		"tags":                "Tags",
		"value":               "Value",
	})

	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
