// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package shield

import (
	"context"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-provider-awscc/internal/generic"
	"github.com/hashicorp/terraform-provider-awscc/internal/identity"
	"github.com/hashicorp/terraform-provider-awscc/internal/registry"
	fwvalidators "github.com/hashicorp/terraform-provider-awscc/internal/validators"
)

func schemaAttribute1ed616d91c3e112bb67e0721() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Part of the key:value pair that defines a tag. You can use a tag value to describe a specific value within a category, such as \"companyA\" or \"companyB.\" Tag values are case-sensitive.",
		Optional:    true,
		Computed:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.LengthBetween(0, 256),
			fwvalidators.NotNullString(),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute317fba22c6c7bdd119d7945a() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Action
			"action": schemaAttributef008be539bf053d564cb2608(),
			// Property: Status
			"status": schemaAttribute51263ace75b7143399536737(),
		}, /*END SCHEMA*/
		Description: "The automatic application layer DDoS mitigation settings for a Protection. This configuration determines whether Shield Advanced automatically manages rules in the web ACL in order to respond to application layer events that Shield Advanced determines to be DDoS attacks.",
		Optional:    true,
		Computed:    true,
		PlanModifiers: []planmodifier.Object{ /*START PLAN MODIFIERS*/
			objectplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute3f85d06fecbe3d622c3280ab() schema.Attribute {
	return (schema.ListAttribute{ /*START ATTRIBUTE*/
		ElementType: types.StringType,
		Description: "The Amazon Resource Names (ARNs) of the health check to associate with the protection.",
		Optional:    true,
		Computed:    true,
		Validators: []validator.List{ /*START VALIDATORS*/
			listvalidator.SizeAtMost(1),
			listvalidator.ValueStringsAre(
				stringvalidator.LengthBetween(1, 2048),
			),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.List{ /*START PLAN MODIFIERS*/
			generic.Multiset(),
			listplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute493badc67c78dadd687b6163() schema.Attribute {
	return (schema.ListNestedAttribute{ /*START ATTRIBUTE*/
		NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Key
				"key": schemaAttributef6d7283ac5194374a95c3086(),
				// Property: Value
				"value": schemaAttribute1ed616d91c3e112bb67e0721(),
			}, /*END SCHEMA*/
		}, /*END NESTED OBJECT*/
		Description: "One or more tag key-value pairs for the Protection object.",
		Optional:    true,
		Computed:    true,
		Validators: []validator.List{ /*START VALIDATORS*/
			listvalidator.SizeAtMost(200),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.List{ /*START PLAN MODIFIERS*/
			generic.Multiset(),
			listplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute51263ace75b7143399536737() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Indicates whether automatic application layer DDoS mitigation is enabled for the protection.",
		Optional:    true,
		Computed:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.OneOf(
				"ENABLED",
				"DISABLED",
			),
			fwvalidators.NotNullString(),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute73233540a64277ecf21832b1() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The unique identifier (ID) of the protection.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute986cf77192e42ac48facdd72() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		CustomType:  jsontypes.NormalizedType{},
		Description: "Specifies that Shield Advanced should configure its AWS WAF rules with the AWS WAF `Block` action.\nYou must specify exactly one action, either `Block` or `Count`.",
		Optional:    true,
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributea5d0f2928108513a818486fe() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The ARN (Amazon Resource Name) of the resource to be protected.",
		Required:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.LengthBetween(1, 2048),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.RequiresReplace(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributeaa5cf9f53850b3b1aca4d260() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		CustomType:  jsontypes.NormalizedType{},
		Description: "Specifies that Shield Advanced should configure its AWS WAF rules with the AWS WAF `Count` action.\nYou must specify exactly one action, either `Block` or `Count`.",
		Optional:    true,
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributeb461bb87176d5dd9f14b7117() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The ARN (Amazon Resource Name) of the protection.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributec3b1c680efdf986b4bc45239() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Friendly name for the Protection.",
		Required:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.LengthBetween(1, 128),
			stringvalidator.RegexMatches(regexp.MustCompile("[ a-zA-Z0-9_\\.\\-]*"), ""),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.RequiresReplace(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributef008be539bf053d564cb2608() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Block
			"block": schemaAttribute986cf77192e42ac48facdd72(),
			// Property: Count
			"count": schemaAttributeaa5cf9f53850b3b1aca4d260(),
		}, /*END SCHEMA*/
		Description: "Specifies the action setting that Shield Advanced should use in the AWS WAF rules that it creates on behalf of the protected resource in response to DDoS attacks. You specify this as part of the configuration for the automatic application layer DDoS mitigation feature, when you enable or update automatic mitigation. Shield Advanced creates the AWS WAF rules in a Shield Advanced-managed rule group, inside the web ACL that you have associated with the resource.",
		Optional:    true,
		Computed:    true,
		Validators: []validator.Object{ /*START VALIDATORS*/
			fwvalidators.NotNullObject(),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.Object{ /*START PLAN MODIFIERS*/
			objectplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributef6d7283ac5194374a95c3086() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Part of the key:value pair that defines a tag. You can use a tag key to describe a category of information, such as \"customer.\" Tag keys are case-sensitive.",
		Optional:    true,
		Computed:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.LengthBetween(1, 128),
			fwvalidators.NotNullString(),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func init() {
	registry.AddResourceFactory("awscc_shield_protection", protectionResource)
	registry.AddListResourceFactory("awscc_shield_protection", generic.NewListResource(protectionResource))
}

// protectionResource returns the Terraform awscc_shield_protection resource.
// This Terraform resource corresponds to the CloudFormation AWS::Shield::Protection resource.
func protectionResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: ApplicationLayerAutomaticResponseConfiguration
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "description": "The automatic application layer DDoS mitigation settings for a Protection. This configuration determines whether Shield Advanced automatically manages rules in the web ACL in order to respond to application layer events that Shield Advanced determines to be DDoS attacks.",
		//	  "properties": {
		//	    "Action": {
		//	      "description": "Specifies the action setting that Shield Advanced should use in the AWS WAF rules that it creates on behalf of the protected resource in response to DDoS attacks. You specify this as part of the configuration for the automatic application layer DDoS mitigation feature, when you enable or update automatic mitigation. Shield Advanced creates the AWS WAF rules in a Shield Advanced-managed rule group, inside the web ACL that you have associated with the resource.",
		//	      "properties": {
		//	        "Block": {
		//	          "additionalProperties": false,
		//	          "description": "Specifies that Shield Advanced should configure its AWS WAF rules with the AWS WAF `Block` action.\nYou must specify exactly one action, either `Block` or `Count`.",
		//	          "type": "object"
		//	        },
		//	        "Count": {
		//	          "additionalProperties": false,
		//	          "description": "Specifies that Shield Advanced should configure its AWS WAF rules with the AWS WAF `Count` action.\nYou must specify exactly one action, either `Block` or `Count`.",
		//	          "type": "object"
		//	        }
		//	      },
		//	      "type": "object"
		//	    },
		//	    "Status": {
		//	      "description": "Indicates whether automatic application layer DDoS mitigation is enabled for the protection.",
		//	      "enum": [
		//	        "ENABLED",
		//	        "DISABLED"
		//	      ],
		//	      "type": "string"
		//	    }
		//	  },
		//	  "required": [
		//	    "Action",
		//	    "Status"
		//	  ],
		//	  "type": "object"
		//	}
		"application_layer_automatic_response_configuration": schemaAttribute317fba22c6c7bdd119d7945a(),
		// Property: HealthCheckArns
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The Amazon Resource Names (ARNs) of the health check to associate with the protection.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "maxLength": 2048,
		//	    "minLength": 1,
		//	    "type": "string"
		//	  },
		//	  "maxItems": 1,
		//	  "type": "array"
		//	}
		"health_check_arns": schemaAttribute3f85d06fecbe3d622c3280ab(),
		// Property: Name
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Friendly name for the Protection.",
		//	  "maxLength": 128,
		//	  "minLength": 1,
		//	  "pattern": "[ a-zA-Z0-9_\\.\\-]*",
		//	  "type": "string"
		//	}
		"name": schemaAttributec3b1c680efdf986b4bc45239(),
		// Property: ProtectionArn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The ARN (Amazon Resource Name) of the protection.",
		//	  "type": "string"
		//	}
		"protection_arn": schemaAttributeb461bb87176d5dd9f14b7117(),
		// Property: ProtectionId
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The unique identifier (ID) of the protection.",
		//	  "type": "string"
		//	}
		"protection_id": schemaAttribute73233540a64277ecf21832b1(),
		// Property: ResourceArn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The ARN (Amazon Resource Name) of the resource to be protected.",
		//	  "maxLength": 2048,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"resource_arn": schemaAttributea5d0f2928108513a818486fe(),
		// Property: Tags
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "One or more tag key-value pairs for the Protection object.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "additionalProperties": false,
		//	    "description": "A tag associated with an AWS resource. Tags are key:value pairs that you can use to categorize and manage your resources, for purposes like billing or other management. Typically, the tag key represents a category, such as \"environment\", and the tag value represents a specific value within that category, such as \"test,\" \"development,\" or \"production\". Or you might set the tag key to \"customer\" and the value to the customer name or ID. You can specify one or more tags to add to each AWS resource, up to 50 tags for a resource.",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "Part of the key:value pair that defines a tag. You can use a tag key to describe a category of information, such as \"customer.\" Tag keys are case-sensitive.",
		//	        "maxLength": 128,
		//	        "minLength": 1,
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Part of the key:value pair that defines a tag. You can use a tag value to describe a specific value within a category, such as \"companyA\" or \"companyB.\" Tag values are case-sensitive.",
		//	        "maxLength": 256,
		//	        "minLength": 0,
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key",
		//	      "Value"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "maxItems": 200,
		//	  "type": "array"
		//	}
		"tags": schemaAttribute493badc67c78dadd687b6163(),
	} /*END SCHEMA*/

	// Corresponds to CloudFormation primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Enables AWS Shield Advanced for a specific AWS resource. The resource can be an Amazon CloudFront distribution, Amazon Route 53 hosted zone, AWS Global Accelerator standard accelerator, Elastic IP Address, Application Load Balancer, or a Classic Load Balancer. You can protect Amazon EC2 instances and Network Load Balancers by association with protected Amazon EC2 Elastic IP addresses.",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudFormationTypeName("AWS::Shield::Protection").WithTerraformTypeName("awscc_shield_protection")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithPrimaryIdentifier(
		identity.Identifier{
			Name:              "protection_arn",
			Description:       "The ARN (Amazon Resource Name) of the protection",
			RequiredForImport: true,
		})

	opts = opts.IsGlobalResourceType(true)
	opts = opts.WithAttributeNameMap(map[string]string{
		"action": "Action",
		"application_layer_automatic_response_configuration": "ApplicationLayerAutomaticResponseConfiguration",
		"block":             "Block",
		"count":             "Count",
		"health_check_arns": "HealthCheckArns",
		"key":               "Key",
		"name":              "Name",
		"protection_arn":    "ProtectionArn",
		"protection_id":     "ProtectionId",
		"resource_arn":      "ResourceArn",
		"status":            "Status",
		"tags":              "Tags",
		"value":             "Value",
	})

	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
