// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package translate

import (
	"context"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-provider-awscc/internal/generic"
	"github.com/hashicorp/terraform-provider-awscc/internal/identity"
	"github.com/hashicorp/terraform-provider-awscc/internal/registry"
	fwvalidators "github.com/hashicorp/terraform-provider-awscc/internal/validators"
)

func schemaAttribute0372ca38b9021f6e1d0e0869() schema.Attribute {
	return (schema.Int64Attribute{ /*START ATTRIBUTE*/
		Description: "The number of records unsuccessfully imported.",
		Computed:    true,
		PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
			int64planmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute04cbd0eb23a42707ffb1d82a() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The Amazon Resource Name (ARN) of the parallel data resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute059ad284d81104555d21159f() schema.Attribute {
	return (schema.ListNestedAttribute{ /*START ATTRIBUTE*/
		NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Key
				"key": schemaAttribute725dd4ce28f7e0b6de71e027(),
				// Property: Value
				"value": schemaAttributee7e5b07f3067b5f356e7f376(),
			}, /*END SCHEMA*/
		}, /*END NESTED OBJECT*/
		Description: "Tags associated with the parallel data resource.",
		Optional:    true,
		Computed:    true,
		Validators: []validator.List{ /*START VALIDATORS*/
			listvalidator.SizeAtMost(200),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.List{ /*START PLAN MODIFIERS*/
			listplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute0a70da2b3bd95aaa301c6a38() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The format of the parallel data input file.",
		Required:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.OneOf(
				"TSV",
				"CSV",
				"TMX",
			),
		}, /*END VALIDATORS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute0e602df49f00a9daa67000e5() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		CustomType:  timetypes.RFC3339Type{},
		Description: "The time at which the parallel data resource was created.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute1dad92d88b5ad182c3adc9cc() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The type of encryption key.",
		Optional:    true,
		Computed:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.OneOf(
				"KMS",
			),
			fwvalidators.NotNullString(),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute2492ab46e28474f9e28efecb() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Id
			"id": schemaAttribute301e215c604001e5cbbc217c(),
			// Property: Type
			"type": schemaAttribute1dad92d88b5ad182c3adc9cc(),
		}, /*END SCHEMA*/
		Description: "The encryption key used to encrypt this object.",
		Optional:    true,
		Computed:    true,
		PlanModifiers: []planmodifier.Object{ /*START PLAN MODIFIERS*/
			objectplanmodifier.UseStateForUnknown(),
			objectplanmodifier.RequiresReplaceIfConfigured(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute301e215c604001e5cbbc217c() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The Amazon Resource Name (ARN) of the encryption key.",
		Optional:    true,
		Computed:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.LengthBetween(1, 400),
			stringvalidator.RegexMatches(regexp.MustCompile("^(arn:aws((-us-gov)|(-iso)|(-iso-b)|(-cn))?:kms:)?([a-z]{2}-[a-z]+(-[a-z]+)?-\\d:)?(\\d{12}:)?(((key/)?[a-zA-Z0-9-_]+)|(alias/[a-zA-Z0-9:/_-]+))$"), ""),
			fwvalidators.NotNullString(),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute3d8168895486cd4eb374935e() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		CustomType:  timetypes.RFC3339Type{},
		Description: "The time at which the parallel data resource was last updated.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute45cc207ddffc02aabae7e51b() schema.Attribute {
	return (schema.ListAttribute{ /*START ATTRIBUTE*/
		ElementType: types.StringType,
		Description: "The language codes for the target languages available in the parallel data file.",
		Computed:    true,
		PlanModifiers: []planmodifier.List{ /*START PLAN MODIFIERS*/
			listplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute45e4ff306e7d4e0b4802e87f() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The source language of the translations in the parallel data file.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute6a901cf546e9f1dc1d1ed749() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The status of the parallel data resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttribute725dd4ce28f7e0b6de71e027() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Optional: true,
		Computed: true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.LengthBetween(1, 128),
			fwvalidators.NotNullString(),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributeb8cb402ac198869e952a0f7a() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "A custom name for the parallel data resource. Must be unique in the account and region.",
		Required:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.LengthBetween(1, 256),
			stringvalidator.RegexMatches(regexp.MustCompile("^([A-Za-z0-9-]_?)+$"), ""),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.RequiresReplace(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributecccc633f0400c35d891b3180() schema.Attribute {
	return (schema.Int64Attribute{ /*START ATTRIBUTE*/
		Description: "The number of records successfully imported.",
		Computed:    true,
		PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
			int64planmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributed39122c252ae902c889af00c() schema.Attribute {
	return (schema.Int64Attribute{ /*START ATTRIBUTE*/
		Description: "The number of items skipped during import.",
		Computed:    true,
		PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
			int64planmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributee7e5b07f3067b5f356e7f376() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Optional: true,
		Computed: true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.LengthBetween(0, 256),
			fwvalidators.NotNullString(),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributee7eca48f5d5d02ce09d6dbd5() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The URI of the Amazon S3 folder that contains the parallel data input file.",
		Required:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.LengthAtMost(1024),
			stringvalidator.RegexMatches(regexp.MustCompile("^s3://[a-z0-9][\\.\\-a-z0-9]{1,61}[a-z0-9](/.*)?$"), ""),
		}, /*END VALIDATORS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributeed78e09660a428305b4183a1() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Format
			"format": schemaAttribute0a70da2b3bd95aaa301c6a38(),
			// Property: S3Uri
			"s3_uri": schemaAttributee7eca48f5d5d02ce09d6dbd5(),
		}, /*END SCHEMA*/
		Description: "Specifies the format and S3 location of the parallel data input file.",
		Required:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributef6acf3557526d3a2dc534e2f() schema.Attribute {
	return (schema.Int64Attribute{ /*START ATTRIBUTE*/
		Description: "The number of UTF-8 characters imported from the parallel data input file.",
		Computed:    true,
		PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
			int64planmodifier.UseStateForUnknown(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func schemaAttributeff3f89b7c603d5fd3d271be8() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "A custom description for the parallel data resource.",
		Optional:    true,
		Computed:    true,
		Validators: []validator.String{ /*START VALIDATORS*/
			stringvalidator.LengthAtMost(256),
		}, /*END VALIDATORS*/
		PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
			stringplanmodifier.UseStateForUnknown(),
			stringplanmodifier.RequiresReplaceIfConfigured(),
		}, /*END PLAN MODIFIERS*/
	} /*END ATTRIBUTE*/)
}

func init() {
	registry.AddResourceFactory("awscc_translate_parallel_data", parallelDataResource)
	registry.AddListResourceFactory("awscc_translate_parallel_data", generic.NewListResource(parallelDataResource))
}

// parallelDataResource returns the Terraform awscc_translate_parallel_data resource.
// This Terraform resource corresponds to the CloudFormation AWS::Translate::ParallelData resource.
func parallelDataResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: Arn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The Amazon Resource Name (ARN) of the parallel data resource.",
		//	  "maxLength": 512,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"arn": schemaAttribute04cbd0eb23a42707ffb1d82a(),
		// Property: CreatedAt
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The time at which the parallel data resource was created.",
		//	  "format": "date-time",
		//	  "type": "string"
		//	}
		"created_at": schemaAttribute0e602df49f00a9daa67000e5(),
		// Property: Description
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "A custom description for the parallel data resource.",
		//	  "maxLength": 256,
		//	  "type": "string"
		//	}
		"description": schemaAttributeff3f89b7c603d5fd3d271be8(),
		// Property: EncryptionKey
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "description": "The encryption key used to encrypt this object.",
		//	  "properties": {
		//	    "Id": {
		//	      "description": "The Amazon Resource Name (ARN) of the encryption key.",
		//	      "maxLength": 400,
		//	      "minLength": 1,
		//	      "pattern": "^(arn:aws((-us-gov)|(-iso)|(-iso-b)|(-cn))?:kms:)?([a-z]{2}-[a-z]+(-[a-z]+)?-\\d:)?(\\d{12}:)?(((key/)?[a-zA-Z0-9-_]+)|(alias/[a-zA-Z0-9:/_-]+))$",
		//	      "type": "string"
		//	    },
		//	    "Type": {
		//	      "description": "The type of encryption key.",
		//	      "enum": [
		//	        "KMS"
		//	      ],
		//	      "type": "string"
		//	    }
		//	  },
		//	  "required": [
		//	    "Type",
		//	    "Id"
		//	  ],
		//	  "type": "object"
		//	}
		"encryption_key": schemaAttribute2492ab46e28474f9e28efecb(),
		// Property: FailedRecordCount
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The number of records unsuccessfully imported.",
		//	  "type": "integer"
		//	}
		"failed_record_count": schemaAttribute0372ca38b9021f6e1d0e0869(),
		// Property: ImportedDataSize
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The number of UTF-8 characters imported from the parallel data input file.",
		//	  "type": "integer"
		//	}
		"imported_data_size": schemaAttributef6acf3557526d3a2dc534e2f(),
		// Property: ImportedRecordCount
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The number of records successfully imported.",
		//	  "type": "integer"
		//	}
		"imported_record_count": schemaAttributecccc633f0400c35d891b3180(),
		// Property: LastUpdatedAt
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The time at which the parallel data resource was last updated.",
		//	  "format": "date-time",
		//	  "type": "string"
		//	}
		"last_updated_at": schemaAttribute3d8168895486cd4eb374935e(),
		// Property: Name
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "A custom name for the parallel data resource. Must be unique in the account and region.",
		//	  "maxLength": 256,
		//	  "minLength": 1,
		//	  "pattern": "^([A-Za-z0-9-]_?)+$",
		//	  "type": "string"
		//	}
		"name": schemaAttributeb8cb402ac198869e952a0f7a(),
		// Property: ParallelDataConfig
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "description": "Specifies the format and S3 location of the parallel data input file.",
		//	  "properties": {
		//	    "Format": {
		//	      "description": "The format of the parallel data input file.",
		//	      "enum": [
		//	        "TSV",
		//	        "CSV",
		//	        "TMX"
		//	      ],
		//	      "type": "string"
		//	    },
		//	    "S3Uri": {
		//	      "description": "The URI of the Amazon S3 folder that contains the parallel data input file.",
		//	      "maxLength": 1024,
		//	      "pattern": "^s3://[a-z0-9][\\.\\-a-z0-9]{1,61}[a-z0-9](/.*)?$",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "required": [
		//	    "S3Uri",
		//	    "Format"
		//	  ],
		//	  "type": "object"
		//	}
		"parallel_data_config": schemaAttributeed78e09660a428305b4183a1(),
		// Property: SkippedRecordCount
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The number of items skipped during import.",
		//	  "type": "integer"
		//	}
		"skipped_record_count": schemaAttributed39122c252ae902c889af00c(),
		// Property: SourceLanguageCode
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The source language of the translations in the parallel data file.",
		//	  "maxLength": 5,
		//	  "minLength": 2,
		//	  "type": "string"
		//	}
		"source_language_code": schemaAttribute45e4ff306e7d4e0b4802e87f(),
		// Property: Status
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The status of the parallel data resource.",
		//	  "enum": [
		//	    "CREATING",
		//	    "UPDATING",
		//	    "ACTIVE",
		//	    "DELETING",
		//	    "FAILED"
		//	  ],
		//	  "type": "string"
		//	}
		"status": schemaAttribute6a901cf546e9f1dc1d1ed749(),
		// Property: Tags
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Tags associated with the parallel data resource.",
		//	  "items": {
		//	    "additionalProperties": false,
		//	    "properties": {
		//	      "Key": {
		//	        "maxLength": 128,
		//	        "minLength": 1,
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "maxLength": 256,
		//	        "minLength": 0,
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key",
		//	      "Value"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "maxItems": 200,
		//	  "type": "array"
		//	}
		"tags": schemaAttribute059ad284d81104555d21159f(),
		// Property: TargetLanguageCodes
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The language codes for the target languages available in the parallel data file.",
		//	  "items": {
		//	    "maxLength": 5,
		//	    "minLength": 2,
		//	    "type": "string"
		//	  },
		//	  "type": "array"
		//	}
		"target_language_codes": schemaAttribute45cc207ddffc02aabae7e51b(),
	} /*END SCHEMA*/

	// Corresponds to CloudFormation primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "A parallel data resource in Amazon Translate used to customize machine translation output.",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudFormationTypeName("AWS::Translate::ParallelData").WithTerraformTypeName("awscc_translate_parallel_data")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithPrimaryIdentifier(
		identity.Identifier{
			Name:              "arn",
			Description:       "The Amazon Resource Name (ARN) of the parallel data resource",
			RequiredForImport: true,
		})

	opts = opts.WithAttributeNameMap(map[string]string{
		"arn":                   "Arn",
		"created_at":            "CreatedAt",
		"description":           "Description",
		"encryption_key":        "EncryptionKey",
		"failed_record_count":   "FailedRecordCount",
		"format":                "Format",
		"id":                    "Id",
		"imported_data_size":    "ImportedDataSize",
		"imported_record_count": "ImportedRecordCount",
		"key":                   "Key",
		"last_updated_at":       "LastUpdatedAt",
		"name":                  "Name",
		"parallel_data_config":  "ParallelDataConfig",
		"s3_uri":                "S3Uri",
		"skipped_record_count":  "SkippedRecordCount",
		"source_language_code":  "SourceLanguageCode",
		"status":                "Status",
		"tags":                  "Tags",
		"target_language_codes": "TargetLanguageCodes",
		"type":                  "Type",
		"value":                 "Value",
	})

	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
