// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package opensearchservice

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-provider-awscc/internal/generic"
	"github.com/hashicorp/terraform-provider-awscc/internal/registry"
)

func schemaAttribute133f140eabb3d9ef5adc3d81() schema.Attribute {
	return (schema.BoolAttribute{ /*START ATTRIBUTE*/
		Description: "Whether Identity Center is enabled.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute162fd516842a1fe356080f90() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Enabled
			"enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: KmsKeyId
			"kms_key_id": schemaAttribute8546b7606a0983e5b019d750(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute1676c3ed216e44e4907c61be() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: EnabledAPIAccess
			"enabled_api_access": schemaAttribute133f140eabb3d9ef5adc3d81(),
			// Property: IdentityCenterApplicationARN
			"identity_center_application_arn": schemaAttribute3cd5aa43e853f4657221630c(),
			// Property: IdentityCenterInstanceARN
			"identity_center_instance_arn": schemaAttributeaaa7c366de8d62f13518ed1d(),
			// Property: IdentityStoreId
			"identity_store_id": schemaAttribute7b4d35477315a4b5882207db(),
			// Property: RolesKey
			"roles_key": schemaAttribute2c27fc45dae2545cf84c60c7(),
			// Property: SubjectKey
			"subject_key": schemaAttributeed56daa0bc04f94576532937(),
		}, /*END SCHEMA*/
		Description: "Options for configuring Identity Center",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute172b4dc2f6ff1d95e2502124() schema.Attribute {
	return (schema.ListNestedAttribute{ /*START ATTRIBUTE*/
		NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: NodeConfig
				"node_config": schemaAttribute845c9ccd6584e1593ebf8b52(),
				// Property: NodeType
				"node_type": schemaAttribute8546b7606a0983e5b019d750(),
			}, /*END SCHEMA*/
		}, /*END NESTED OBJECT*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute240784d994d54753f6163ed1() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		CustomType: jsontypes.NormalizedType{},
		Computed:   true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute2c27fc45dae2545cf84c60c7() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The roles key for Identity Center options.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute3cd5aa43e853f4657221630c() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The ARN of the Identity Center application.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute400b91f695cfb6dc1de20879() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: AutomatedSnapshotStartHour
			"automated_snapshot_start_hour": schemaAttribute7a0b077565964110b591416c(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute4029f9cad732ca3a3a7c4bc0() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Enabled
			"enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: RolesKey
			"roles_key": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: SubjectKey
			"subject_key": schemaAttribute8546b7606a0983e5b019d750(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute45930cdacd6bcf444ba52926() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: MasterUserARN
			"master_user_arn": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: MasterUserName
			"master_user_name": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: MasterUserPassword
			"master_user_password": schemaAttribute8546b7606a0983e5b019d750(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute4b2a082a4a2b271e1a233648() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: ColdStorageOptions
			"cold_storage_options": schemaAttributee1916637616a9e7af0d58527(),
			// Property: DedicatedMasterCount
			"dedicated_master_count": schemaAttribute7a0b077565964110b591416c(),
			// Property: DedicatedMasterEnabled
			"dedicated_master_enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: DedicatedMasterType
			"dedicated_master_type": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: InstanceCount
			"instance_count": schemaAttribute7a0b077565964110b591416c(),
			// Property: InstanceType
			"instance_type": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: MultiAZWithStandbyEnabled
			"multi_az_with_standby_enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: NodeOptions
			"node_options": schemaAttribute172b4dc2f6ff1d95e2502124(),
			// Property: WarmCount
			"warm_count": schemaAttribute7a0b077565964110b591416c(),
			// Property: WarmEnabled
			"warm_enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: WarmType
			"warm_type": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: ZoneAwarenessConfig
			"zone_awareness_config": schemaAttribute69db195f1f7f4044fb832ae8(),
			// Property: ZoneAwarenessEnabled
			"zone_awareness_enabled": schemaAttribute6d6d970b325181468fb85ac7(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute6101942e01a41edd8005c884() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: EntityId
			"entity_id": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: MetadataContent
			"metadata_content": schemaAttribute8546b7606a0983e5b019d750(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute666ed416252c506ad1f51998() schema.Attribute {
	return (
	// Pattern: ""
	schema.MapAttribute{ /*START ATTRIBUTE*/
		ElementType: types.StringType,
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute69db195f1f7f4044fb832ae8() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: AvailabilityZoneCount
			"availability_zone_count": schemaAttribute7a0b077565964110b591416c(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute6b19d70428f775d7b279a7da() schema.Attribute {
	return (schema.BoolAttribute{ /*START ATTRIBUTE*/
		Description: "Whether to enable serverless vector acceleration.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute6d6d970b325181468fb85ac7() schema.Attribute {
	return (schema.BoolAttribute{ /*START ATTRIBUTE*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute723a5cf7ee134917cada0da1() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The key of the tag.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute72f1226eacdae8f7c48bf4e5() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: AutomatedUpdateDate
			"automated_update_date": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: Cancellable
			"cancellable": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: CurrentVersion
			"current_version": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: Description
			"description": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: NewVersion
			"new_version": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: OptionalDeployment
			"optional_deployment": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: UpdateAvailable
			"update_available": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: UpdateStatus
			"update_status": schemaAttribute8546b7606a0983e5b019d750(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute7a0b077565964110b591416c() schema.Attribute {
	return (schema.Int64Attribute{ /*START ATTRIBUTE*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute7b4d35477315a4b5882207db() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The IdentityStoreId for Identity Center options.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute81f30437abce0914d193ae45() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Enabled
			"enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: OffPeakWindow
			"off_peak_window": schemaAttributed87fea75e7e8947417ea0642(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute82d3d0dc6303f84fdf9e6c80() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Hours
			"hours": schemaAttribute7a0b077565964110b591416c(),
			// Property: Minutes
			"minutes": schemaAttribute7a0b077565964110b591416c(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute8331a1064b7e5b21da399aa5() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: EBSEnabled
			"ebs_enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: Iops
			"iops": schemaAttribute7a0b077565964110b591416c(),
			// Property: Throughput
			"throughput": schemaAttribute7a0b077565964110b591416c(),
			// Property: VolumeSize
			"volume_size": schemaAttribute7a0b077565964110b591416c(),
			// Property: VolumeType
			"volume_type": schemaAttribute8546b7606a0983e5b019d750(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute845c9ccd6584e1593ebf8b52() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Count
			"count": schemaAttribute7a0b077565964110b591416c(),
			// Property: Enabled
			"enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: Type
			"type": schemaAttribute8546b7606a0983e5b019d750(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute8546b7606a0983e5b019d750() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute8b41748b2596ba7c5d349e50() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The engine mode of the domain. Determines whether the domain runs the standard (GENERAL) engine or the optimized multi-engine (OPTIMIZED) engine. This value cannot be changed after the domain is created.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute95397aa89c811abd50fccd4b() schema.Attribute {
	return (schema.BoolAttribute{ /*START ATTRIBUTE*/
		Description: "Controls whether egress traffic from the domain is routed through the customer VPC.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute9a2712ff744367a5c259baa8() schema.Attribute {
	return (schema.BoolAttribute{ /*START ATTRIBUTE*/
		Description: "Whether to enable S3 vectors engine.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute9c6e1b9802ca107b5cf3c2fd() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Enabled
			"enabled": schemaAttribute6b19d70428f775d7b279a7da(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute9ed164c1ee90ee083b6386fb() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: S3VectorsEngine
			"s3_vectors_engine": schemaAttributeaeb0cf0842b3e911175731f7(),
			// Property: ServerlessVectorAcceleration
			"serverless_vector_acceleration": schemaAttribute9c6e1b9802ca107b5cf3c2fd(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute9f344cb5889b911f160270eb() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Enabled
			"enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: IdentityPoolId
			"identity_pool_id": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: RoleArn
			"role_arn": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: UserPoolId
			"user_pool_id": schemaAttribute8546b7606a0983e5b019d750(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute9f957e2ba316edd3f305a4a8() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The value of the tag.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributea1a399cfb1c15d54d613e83e() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: AutoSoftwareUpdateEnabled
			"auto_software_update_enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: UseLatestServiceSoftwareForBlueGreen
			"use_latest_service_software_for_blue_green": schemaAttribute6d6d970b325181468fb85ac7(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributeaaa7c366de8d62f13518ed1d() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The ARN of the Identity Center instance.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributead5b13003f4ee112f08b76a8() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: CustomEndpoint
			"custom_endpoint": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: CustomEndpointCertificateArn
			"custom_endpoint_certificate_arn": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: CustomEndpointEnabled
			"custom_endpoint_enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: EnforceHTTPS
			"enforce_https": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: TLSSecurityPolicy
			"tls_security_policy": schemaAttribute8546b7606a0983e5b019d750(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributeaeb0cf0842b3e911175731f7() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Enabled
			"enabled": schemaAttribute9a2712ff744367a5c259baa8(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributec218e5b3c486be46bd113e81() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Enabled
			"enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: EndTime
			"end_time": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: StartTime
			"start_time": schemaAttribute8546b7606a0983e5b019d750(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributec5cf83a634f331b2a8871ce0() schema.Attribute {
	return (schema.ListAttribute{ /*START ATTRIBUTE*/
		ElementType: types.StringType,
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributecb03b57c92d314743200e5be() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: DeploymentStrategy
			"deployment_strategy": schemaAttribute8546b7606a0983e5b019d750(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributecb5370eea4aa21999209e1b3() schema.Attribute {
	return (
	// Pattern: ""
	schema.MapNestedAttribute{ /*START ATTRIBUTE*/
		NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: CloudWatchLogsLogGroupArn
				"cloudwatch_logs_log_group_arn": schemaAttribute8546b7606a0983e5b019d750(),
				// Property: Enabled
				"enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			}, /*END SCHEMA*/
		}, /*END NESTED OBJECT*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributed17a01db9334cc79b8d16e58() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: EgressEnabled
			"egress_enabled": schemaAttribute95397aa89c811abd50fccd4b(),
			// Property: SecurityGroupIds
			"security_group_ids": schemaAttributec5cf83a634f331b2a8871ce0(),
			// Property: SubnetIds
			"subnet_ids": schemaAttributec5cf83a634f331b2a8871ce0(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributed87fea75e7e8947417ea0642() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: WindowStartTime
			"window_start_time": schemaAttribute82d3d0dc6303f84fdf9e6c80(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributeda6c9c4406d11a9f9bcb0cff() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Enabled
			"enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: PublicKey
			"public_key": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: RolesKey
			"roles_key": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: SubjectKey
			"subject_key": schemaAttribute8546b7606a0983e5b019d750(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributedbd4073583ce8e23f9c95ac5() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The primary use case of the domain. Determines the default configuration tuned for the workload. For GENERAL engine-mode domains, this value can be changed after creation. For OPTIMIZED engine-mode domains, this value cannot be changed after creation.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributeddb68cbe8b7484d9491992f1() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Enabled
			"enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: Idp
			"idp": schemaAttribute6101942e01a41edd8005c884(),
			// Property: MasterBackendRole
			"master_backend_role": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: MasterUserName
			"master_user_name": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: RolesKey
			"roles_key": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: SessionTimeoutMinutes
			"session_timeout_minutes": schemaAttribute7a0b077565964110b591416c(),
			// Property: SubjectKey
			"subject_key": schemaAttribute8546b7606a0983e5b019d750(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributeded73fa7dbd53804cd203b29() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: AnonymousAuthDisableDate
			"anonymous_auth_disable_date": schemaAttribute8546b7606a0983e5b019d750(),
			// Property: AnonymousAuthEnabled
			"anonymous_auth_enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: Enabled
			"enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: IAMFederationOptions
			"iam_federation_options": schemaAttribute4029f9cad732ca3a3a7c4bc0(),
			// Property: InternalUserDatabaseEnabled
			"internal_user_database_enabled": schemaAttribute6d6d970b325181468fb85ac7(),
			// Property: JWTOptions
			"jwt_options": schemaAttributeda6c9c4406d11a9f9bcb0cff(),
			// Property: MasterUserOptions
			"master_user_options": schemaAttribute45930cdacd6bcf444ba52926(),
			// Property: SAMLOptions
			"saml_options": schemaAttributeddb68cbe8b7484d9491992f1(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributee1916637616a9e7af0d58527() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: Enabled
			"enabled": schemaAttribute6d6d970b325181468fb85ac7(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributee7a36bd7567ce5bed8f5325e() schema.Attribute {
	return (schema.ListNestedAttribute{ /*START ATTRIBUTE*/
		NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Key
				"key": schemaAttribute9f957e2ba316edd3f305a4a8(),
				// Property: Value
				"value": schemaAttribute723a5cf7ee134917cada0da1(),
			}, /*END SCHEMA*/
		}, /*END NESTED OBJECT*/
		Description: "An arbitrary set of tags (key-value pairs) for this Domain.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributeed56daa0bc04f94576532937() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The subject key for Identity Center options.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func init() {
	registry.AddDataSourceFactory("awscc_opensearchservice_domain", domainDataSource)
}

// domainDataSource returns the Terraform awscc_opensearchservice_domain data source.
// This Terraform data source corresponds to the CloudFormation AWS::OpenSearchService::Domain resource.
func domainDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AIMLOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "S3VectorsEngine": {
		//	      "additionalProperties": false,
		//	      "properties": {
		//	        "Enabled": {
		//	          "description": "Whether to enable S3 vectors engine.",
		//	          "type": "boolean"
		//	        }
		//	      },
		//	      "required": [
		//	        "Enabled"
		//	      ],
		//	      "type": "object"
		//	    },
		//	    "ServerlessVectorAcceleration": {
		//	      "additionalProperties": false,
		//	      "properties": {
		//	        "Enabled": {
		//	          "description": "Whether to enable serverless vector acceleration.",
		//	          "type": "boolean"
		//	        }
		//	      },
		//	      "type": "object"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"aiml_options": schemaAttribute9ed164c1ee90ee083b6386fb(),
		// Property: AccessPolicies
		// CloudFormation resource type schema:
		//
		//	{
		//	  "type": "object"
		//	}
		"access_policies": schemaAttribute240784d994d54753f6163ed1(),
		// Property: AdvancedOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "patternProperties": {
		//	    "": {
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"advanced_options": schemaAttribute666ed416252c506ad1f51998(),
		// Property: AdvancedSecurityOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "AnonymousAuthDisableDate": {
		//	      "type": "string"
		//	    },
		//	    "AnonymousAuthEnabled": {
		//	      "type": "boolean"
		//	    },
		//	    "Enabled": {
		//	      "type": "boolean"
		//	    },
		//	    "IAMFederationOptions": {
		//	      "additionalProperties": false,
		//	      "properties": {
		//	        "Enabled": {
		//	          "type": "boolean"
		//	        },
		//	        "RolesKey": {
		//	          "type": "string"
		//	        },
		//	        "SubjectKey": {
		//	          "type": "string"
		//	        }
		//	      },
		//	      "type": "object"
		//	    },
		//	    "InternalUserDatabaseEnabled": {
		//	      "type": "boolean"
		//	    },
		//	    "JWTOptions": {
		//	      "additionalProperties": false,
		//	      "properties": {
		//	        "Enabled": {
		//	          "type": "boolean"
		//	        },
		//	        "PublicKey": {
		//	          "type": "string"
		//	        },
		//	        "RolesKey": {
		//	          "type": "string"
		//	        },
		//	        "SubjectKey": {
		//	          "type": "string"
		//	        }
		//	      },
		//	      "type": "object"
		//	    },
		//	    "MasterUserOptions": {
		//	      "additionalProperties": false,
		//	      "properties": {
		//	        "MasterUserARN": {
		//	          "type": "string"
		//	        },
		//	        "MasterUserName": {
		//	          "type": "string"
		//	        },
		//	        "MasterUserPassword": {
		//	          "type": "string"
		//	        }
		//	      },
		//	      "type": "object"
		//	    },
		//	    "SAMLOptions": {
		//	      "additionalProperties": false,
		//	      "properties": {
		//	        "Enabled": {
		//	          "type": "boolean"
		//	        },
		//	        "Idp": {
		//	          "additionalProperties": false,
		//	          "properties": {
		//	            "EntityId": {
		//	              "type": "string"
		//	            },
		//	            "MetadataContent": {
		//	              "maxLength": 1048576,
		//	              "minLength": 1,
		//	              "type": "string"
		//	            }
		//	          },
		//	          "required": [
		//	            "MetadataContent",
		//	            "EntityId"
		//	          ],
		//	          "type": "object"
		//	        },
		//	        "MasterBackendRole": {
		//	          "type": "string"
		//	        },
		//	        "MasterUserName": {
		//	          "type": "string"
		//	        },
		//	        "RolesKey": {
		//	          "type": "string"
		//	        },
		//	        "SessionTimeoutMinutes": {
		//	          "type": "integer"
		//	        },
		//	        "SubjectKey": {
		//	          "type": "string"
		//	        }
		//	      },
		//	      "type": "object"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"advanced_security_options": schemaAttributeded73fa7dbd53804cd203b29(),
		// Property: Arn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "type": "string"
		//	}
		"arn": schemaAttribute8546b7606a0983e5b019d750(),
		// Property: AutomatedSnapshotPauseOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "Enabled": {
		//	      "type": "boolean"
		//	    },
		//	    "EndTime": {
		//	      "type": "string"
		//	    },
		//	    "StartTime": {
		//	      "type": "string"
		//	    }
		//	  },
		//	  "required": [
		//	    "Enabled"
		//	  ],
		//	  "type": "object"
		//	}
		"automated_snapshot_pause_options": schemaAttributec218e5b3c486be46bd113e81(),
		// Property: ClusterConfig
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "ColdStorageOptions": {
		//	      "additionalProperties": false,
		//	      "properties": {
		//	        "Enabled": {
		//	          "type": "boolean"
		//	        }
		//	      },
		//	      "type": "object"
		//	    },
		//	    "DedicatedMasterCount": {
		//	      "type": "integer"
		//	    },
		//	    "DedicatedMasterEnabled": {
		//	      "type": "boolean"
		//	    },
		//	    "DedicatedMasterType": {
		//	      "type": "string"
		//	    },
		//	    "InstanceCount": {
		//	      "type": "integer"
		//	    },
		//	    "InstanceType": {
		//	      "type": "string"
		//	    },
		//	    "MultiAZWithStandbyEnabled": {
		//	      "type": "boolean"
		//	    },
		//	    "NodeOptions": {
		//	      "items": {
		//	        "additionalProperties": false,
		//	        "properties": {
		//	          "NodeConfig": {
		//	            "additionalProperties": false,
		//	            "properties": {
		//	              "Count": {
		//	                "type": "integer"
		//	              },
		//	              "Enabled": {
		//	                "type": "boolean"
		//	              },
		//	              "Type": {
		//	                "type": "string"
		//	              }
		//	            },
		//	            "type": "object"
		//	          },
		//	          "NodeType": {
		//	            "enum": [
		//	              "coordinator"
		//	            ],
		//	            "type": "string"
		//	          }
		//	        },
		//	        "type": "object"
		//	      },
		//	      "type": "array"
		//	    },
		//	    "WarmCount": {
		//	      "type": "integer"
		//	    },
		//	    "WarmEnabled": {
		//	      "type": "boolean"
		//	    },
		//	    "WarmType": {
		//	      "type": "string"
		//	    },
		//	    "ZoneAwarenessConfig": {
		//	      "additionalProperties": false,
		//	      "properties": {
		//	        "AvailabilityZoneCount": {
		//	          "type": "integer"
		//	        }
		//	      },
		//	      "type": "object"
		//	    },
		//	    "ZoneAwarenessEnabled": {
		//	      "type": "boolean"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"cluster_config": schemaAttribute4b2a082a4a2b271e1a233648(),
		// Property: CognitoOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "Enabled": {
		//	      "type": "boolean"
		//	    },
		//	    "IdentityPoolId": {
		//	      "type": "string"
		//	    },
		//	    "RoleArn": {
		//	      "type": "string"
		//	    },
		//	    "UserPoolId": {
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"cognito_options": schemaAttribute9f344cb5889b911f160270eb(),
		// Property: DeploymentStrategyOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "DeploymentStrategy": {
		//	      "enum": [
		//	        "Default",
		//	        "CapacityOptimized"
		//	      ],
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"deployment_strategy_options": schemaAttributecb03b57c92d314743200e5be(),
		// Property: DomainArn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "type": "string"
		//	}
		"domain_arn": schemaAttribute8546b7606a0983e5b019d750(),
		// Property: DomainEndpoint
		// CloudFormation resource type schema:
		//
		//	{
		//	  "type": "string"
		//	}
		"domain_endpoint": schemaAttribute8546b7606a0983e5b019d750(),
		// Property: DomainEndpointOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "CustomEndpoint": {
		//	      "type": "string"
		//	    },
		//	    "CustomEndpointCertificateArn": {
		//	      "type": "string"
		//	    },
		//	    "CustomEndpointEnabled": {
		//	      "type": "boolean"
		//	    },
		//	    "EnforceHTTPS": {
		//	      "type": "boolean"
		//	    },
		//	    "TLSSecurityPolicy": {
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"domain_endpoint_options": schemaAttributead5b13003f4ee112f08b76a8(),
		// Property: DomainEndpointV2
		// CloudFormation resource type schema:
		//
		//	{
		//	  "type": "string"
		//	}
		"domain_endpoint_v2": schemaAttribute8546b7606a0983e5b019d750(),
		// Property: DomainEndpoints
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "patternProperties": {
		//	    "": {
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"domain_endpoints": schemaAttribute666ed416252c506ad1f51998(),
		// Property: DomainName
		// CloudFormation resource type schema:
		//
		//	{
		//	  "type": "string"
		//	}
		"domain_name": schemaAttribute8546b7606a0983e5b019d750(),
		// Property: EBSOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "EBSEnabled": {
		//	      "type": "boolean"
		//	    },
		//	    "Iops": {
		//	      "type": "integer"
		//	    },
		//	    "Throughput": {
		//	      "type": "integer"
		//	    },
		//	    "VolumeSize": {
		//	      "type": "integer"
		//	    },
		//	    "VolumeType": {
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"ebs_options": schemaAttribute8331a1064b7e5b21da399aa5(),
		// Property: EncryptionAtRestOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "Enabled": {
		//	      "type": "boolean"
		//	    },
		//	    "KmsKeyId": {
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"encryption_at_rest_options": schemaAttribute162fd516842a1fe356080f90(),
		// Property: EngineMode
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The engine mode of the domain. Determines whether the domain runs the standard (GENERAL) engine or the optimized multi-engine (OPTIMIZED) engine. This value cannot be changed after the domain is created.",
		//	  "enum": [
		//	    "GENERAL",
		//	    "OPTIMIZED"
		//	  ],
		//	  "type": "string"
		//	}
		"engine_mode": schemaAttribute8b41748b2596ba7c5d349e50(),
		// Property: EngineVersion
		// CloudFormation resource type schema:
		//
		//	{
		//	  "type": "string"
		//	}
		"engine_version": schemaAttribute8546b7606a0983e5b019d750(),
		// Property: IPAddressType
		// CloudFormation resource type schema:
		//
		//	{
		//	  "type": "string"
		//	}
		"ip_address_type": schemaAttribute8546b7606a0983e5b019d750(),
		// Property: Id
		// CloudFormation resource type schema:
		//
		//	{
		//	  "type": "string"
		//	}
		"domain_id": schemaAttribute8546b7606a0983e5b019d750(),
		// Property: IdentityCenterOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "description": "Options for configuring Identity Center",
		//	  "properties": {
		//	    "EnabledAPIAccess": {
		//	      "description": "Whether Identity Center is enabled.",
		//	      "type": "boolean"
		//	    },
		//	    "IdentityCenterApplicationARN": {
		//	      "description": "The ARN of the Identity Center application.",
		//	      "type": "string"
		//	    },
		//	    "IdentityCenterInstanceARN": {
		//	      "description": "The ARN of the Identity Center instance.",
		//	      "type": "string"
		//	    },
		//	    "IdentityStoreId": {
		//	      "description": "The IdentityStoreId for Identity Center options.",
		//	      "type": "string"
		//	    },
		//	    "RolesKey": {
		//	      "description": "The roles key for Identity Center options.",
		//	      "enum": [
		//	        "GroupName",
		//	        "GroupId"
		//	      ],
		//	      "type": "string"
		//	    },
		//	    "SubjectKey": {
		//	      "description": "The subject key for Identity Center options.",
		//	      "enum": [
		//	        "UserName",
		//	        "UserId",
		//	        "Email"
		//	      ],
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"identity_center_options": schemaAttribute1676c3ed216e44e4907c61be(),
		// Property: LogPublishingOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "patternProperties": {
		//	    "": {
		//	      "additionalProperties": false,
		//	      "properties": {
		//	        "CloudWatchLogsLogGroupArn": {
		//	          "type": "string"
		//	        },
		//	        "Enabled": {
		//	          "type": "boolean"
		//	        }
		//	      },
		//	      "type": "object"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"log_publishing_options": schemaAttributecb5370eea4aa21999209e1b3(),
		// Property: NodeToNodeEncryptionOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "Enabled": {
		//	      "type": "boolean"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"node_to_node_encryption_options": schemaAttributee1916637616a9e7af0d58527(),
		// Property: OffPeakWindowOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "Enabled": {
		//	      "type": "boolean"
		//	    },
		//	    "OffPeakWindow": {
		//	      "additionalProperties": false,
		//	      "properties": {
		//	        "WindowStartTime": {
		//	          "additionalProperties": false,
		//	          "properties": {
		//	            "Hours": {
		//	              "maximum": 23,
		//	              "minimum": 0,
		//	              "type": "integer"
		//	            },
		//	            "Minutes": {
		//	              "maximum": 59,
		//	              "minimum": 0,
		//	              "type": "integer"
		//	            }
		//	          },
		//	          "required": [
		//	            "Hours",
		//	            "Minutes"
		//	          ],
		//	          "type": "object"
		//	        }
		//	      },
		//	      "type": "object"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"off_peak_window_options": schemaAttribute81f30437abce0914d193ae45(),
		// Property: ServiceSoftwareOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "AutomatedUpdateDate": {
		//	      "type": "string"
		//	    },
		//	    "Cancellable": {
		//	      "type": "boolean"
		//	    },
		//	    "CurrentVersion": {
		//	      "type": "string"
		//	    },
		//	    "Description": {
		//	      "type": "string"
		//	    },
		//	    "NewVersion": {
		//	      "type": "string"
		//	    },
		//	    "OptionalDeployment": {
		//	      "type": "boolean"
		//	    },
		//	    "UpdateAvailable": {
		//	      "type": "boolean"
		//	    },
		//	    "UpdateStatus": {
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"service_software_options": schemaAttribute72f1226eacdae8f7c48bf4e5(),
		// Property: SkipShardMigrationWait
		// CloudFormation resource type schema:
		//
		//	{
		//	  "type": "boolean"
		//	}
		"skip_shard_migration_wait": schemaAttribute6d6d970b325181468fb85ac7(),
		// Property: SnapshotOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "AutomatedSnapshotStartHour": {
		//	      "type": "integer"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"snapshot_options": schemaAttribute400b91f695cfb6dc1de20879(),
		// Property: SoftwareUpdateOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "AutoSoftwareUpdateEnabled": {
		//	      "type": "boolean"
		//	    },
		//	    "UseLatestServiceSoftwareForBlueGreen": {
		//	      "type": "boolean"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"software_update_options": schemaAttributea1a399cfb1c15d54d613e83e(),
		// Property: Tags
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "An arbitrary set of tags (key-value pairs) for this Domain.",
		//	  "items": {
		//	    "additionalProperties": false,
		//	    "properties": {
		//	      "Key": {
		//	        "description": "The value of the tag.",
		//	        "maxLength": 128,
		//	        "minLength": 0,
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "The key of the tag.",
		//	        "maxLength": 256,
		//	        "minLength": 0,
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Value",
		//	      "Key"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schemaAttributee7a36bd7567ce5bed8f5325e(),
		// Property: UseCase
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The primary use case of the domain. Determines the default configuration tuned for the workload. For GENERAL engine-mode domains, this value can be changed after creation. For OPTIMIZED engine-mode domains, this value cannot be changed after creation.",
		//	  "enum": [
		//	    "SEARCH",
		//	    "VECTOR",
		//	    "OBSERVABILITY",
		//	    "MIXED"
		//	  ],
		//	  "type": "string"
		//	}
		"use_case": schemaAttributedbd4073583ce8e23f9c95ac5(),
		// Property: VPCOptions
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "properties": {
		//	    "EgressEnabled": {
		//	      "description": "Controls whether egress traffic from the domain is routed through the customer VPC.",
		//	      "type": "boolean"
		//	    },
		//	    "SecurityGroupIds": {
		//	      "items": {
		//	        "type": "string"
		//	      },
		//	      "type": "array",
		//	      "uniqueItems": true
		//	    },
		//	    "SubnetIds": {
		//	      "items": {
		//	        "type": "string"
		//	      },
		//	      "type": "array",
		//	      "uniqueItems": true
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"vpc_options": schemaAttributed17a01db9334cc79b8d16e58(),
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for AWS::OpenSearchService::Domain",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudFormationTypeName("AWS::OpenSearchService::Domain").WithTerraformTypeName("awscc_opensearchservice_domain")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"access_policies":                  "AccessPolicies",
		"advanced_options":                 "AdvancedOptions",
		"advanced_security_options":        "AdvancedSecurityOptions",
		"aiml_options":                     "AIMLOptions",
		"anonymous_auth_disable_date":      "AnonymousAuthDisableDate",
		"anonymous_auth_enabled":           "AnonymousAuthEnabled",
		"arn":                              "Arn",
		"auto_software_update_enabled":     "AutoSoftwareUpdateEnabled",
		"automated_snapshot_pause_options": "AutomatedSnapshotPauseOptions",
		"automated_snapshot_start_hour":    "AutomatedSnapshotStartHour",
		"automated_update_date":            "AutomatedUpdateDate",
		"availability_zone_count":          "AvailabilityZoneCount",
		"cancellable":                      "Cancellable",
		"cloudwatch_logs_log_group_arn":    "CloudWatchLogsLogGroupArn",
		"cluster_config":                   "ClusterConfig",
		"cognito_options":                  "CognitoOptions",
		"cold_storage_options":             "ColdStorageOptions",
		"count":                            "Count",
		"current_version":                  "CurrentVersion",
		"custom_endpoint":                  "CustomEndpoint",
		"custom_endpoint_certificate_arn":  "CustomEndpointCertificateArn",
		"custom_endpoint_enabled":          "CustomEndpointEnabled",
		"dedicated_master_count":           "DedicatedMasterCount",
		"dedicated_master_enabled":         "DedicatedMasterEnabled",
		"dedicated_master_type":            "DedicatedMasterType",
		"deployment_strategy":              "DeploymentStrategy",
		"deployment_strategy_options":      "DeploymentStrategyOptions",
		"description":                      "Description",
		"domain_arn":                       "DomainArn",
		"domain_endpoint":                  "DomainEndpoint",
		"domain_endpoint_options":          "DomainEndpointOptions",
		"domain_endpoint_v2":               "DomainEndpointV2",
		"domain_endpoints":                 "DomainEndpoints",
		"domain_id":                        "Id",
		"domain_name":                      "DomainName",
		"ebs_enabled":                      "EBSEnabled",
		"ebs_options":                      "EBSOptions",
		"egress_enabled":                   "EgressEnabled",
		"enabled":                          "Enabled",
		"enabled_api_access":               "EnabledAPIAccess",
		"encryption_at_rest_options":       "EncryptionAtRestOptions",
		"end_time":                         "EndTime",
		"enforce_https":                    "EnforceHTTPS",
		"engine_mode":                      "EngineMode",
		"engine_version":                   "EngineVersion",
		"entity_id":                        "EntityId",
		"hours":                            "Hours",
		"iam_federation_options":           "IAMFederationOptions",
		"identity_center_application_arn":  "IdentityCenterApplicationARN",
		"identity_center_instance_arn":     "IdentityCenterInstanceARN",
		"identity_center_options":          "IdentityCenterOptions",
		"identity_pool_id":                 "IdentityPoolId",
		"identity_store_id":                "IdentityStoreId",
		"idp":                              "Idp",
		"instance_count":                   "InstanceCount",
		"instance_type":                    "InstanceType",
		"internal_user_database_enabled":   "InternalUserDatabaseEnabled",
		"iops":                             "Iops",
		"ip_address_type":                  "IPAddressType",
		"jwt_options":                      "JWTOptions",
		"key":                              "Key",
		"kms_key_id":                       "KmsKeyId",
		"log_publishing_options":           "LogPublishingOptions",
		"master_backend_role":              "MasterBackendRole",
		"master_user_arn":                  "MasterUserARN",
		"master_user_name":                 "MasterUserName",
		"master_user_options":              "MasterUserOptions",
		"master_user_password":             "MasterUserPassword",
		"metadata_content":                 "MetadataContent",
		"minutes":                          "Minutes",
		"multi_az_with_standby_enabled":    "MultiAZWithStandbyEnabled",
		"new_version":                      "NewVersion",
		"node_config":                      "NodeConfig",
		"node_options":                     "NodeOptions",
		"node_to_node_encryption_options":  "NodeToNodeEncryptionOptions",
		"node_type":                        "NodeType",
		"off_peak_window":                  "OffPeakWindow",
		"off_peak_window_options":          "OffPeakWindowOptions",
		"optional_deployment":              "OptionalDeployment",
		"public_key":                       "PublicKey",
		"role_arn":                         "RoleArn",
		"roles_key":                        "RolesKey",
		"s3_vectors_engine":                "S3VectorsEngine",
		"saml_options":                     "SAMLOptions",
		"security_group_ids":               "SecurityGroupIds",
		"serverless_vector_acceleration":   "ServerlessVectorAcceleration",
		"service_software_options":         "ServiceSoftwareOptions",
		"session_timeout_minutes":          "SessionTimeoutMinutes",
		"skip_shard_migration_wait":        "SkipShardMigrationWait",
		"snapshot_options":                 "SnapshotOptions",
		"software_update_options":          "SoftwareUpdateOptions",
		"start_time":                       "StartTime",
		"subject_key":                      "SubjectKey",
		"subnet_ids":                       "SubnetIds",
		"tags":                             "Tags",
		"throughput":                       "Throughput",
		"tls_security_policy":              "TLSSecurityPolicy",
		"type":                             "Type",
		"update_available":                 "UpdateAvailable",
		"update_status":                    "UpdateStatus",
		"use_case":                         "UseCase",
		"use_latest_service_software_for_blue_green": "UseLatestServiceSoftwareForBlueGreen",
		"user_pool_id":           "UserPoolId",
		"value":                  "Value",
		"volume_size":            "VolumeSize",
		"volume_type":            "VolumeType",
		"vpc_options":            "VPCOptions",
		"warm_count":             "WarmCount",
		"warm_enabled":           "WarmEnabled",
		"warm_type":              "WarmType",
		"window_start_time":      "WindowStartTime",
		"zone_awareness_config":  "ZoneAwarenessConfig",
		"zone_awareness_enabled": "ZoneAwarenessEnabled",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
