// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package transfer

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-provider-awscc/internal/generic"
	"github.com/hashicorp/terraform-provider-awscc/internal/registry"
)

func schemaAttribute0110e43d05afe42636c01b9f() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Specifies whether to use the AWS S3 object content-type as the content-type for the AS2 message.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute013a78830d188e93d6719a3d() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "A unique identifier for the partner profile.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute01a07b4d4c72a15fb793d329() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Specifies the unique Amazon Resource Name (ARN) for the connector.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute06acf0b4e0df0d313e7a71e7() schema.Attribute {
	return (schema.ListAttribute{ /*START ATTRIBUTE*/
		ElementType: types.StringType,
		Description: "The list of egress IP addresses of this connector. These IP addresses are assigned automatically when you create the connector.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute1081705d64512489570f63c0() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "A unique identifier for the connector.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute142b2bfefcd2a991e5bca0b7() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute185000b0dc44c4b2488c99c9() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Signing algorithm for this AS2 connector configuration.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute1b29d4dbf4682e7a255a2343() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "IP address type for Connector",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute1b3bdff5b72b8a35ccdd50d3() schema.Attribute {
	return (schema.Int64Attribute{ /*START ATTRIBUTE*/
		Description: "Port to connect to on the target VPC Lattice resource",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute2619d290bc51f2147fcb24f9() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Specifies the egress type for the connector.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute27486c4779fd780958061426() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "ARN of the VPC Lattice resource configuration",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute2f5c9b132bee8150bfa1e8d5() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Security policy for SFTP Connector",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute30e8a5bc594a2e903c973cb6() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: AsyncMdnConfig
			"async_mdn_config": schemaAttribute95a2b0812ab402ea4be600ed(),
			// Property: BasicAuthSecretId
			"basic_auth_secret_id": schemaAttribute4ef5dac8330b4f06ac810a34(),
			// Property: Compression
			"compression": schemaAttribute5005333c1391c22c0c705a83(),
			// Property: EncryptionAlgorithm
			"encryption_algorithm": schemaAttribute56515eecfef7770f29055e81(),
			// Property: LocalProfileId
			"local_profile_id": schemaAttributed20b0d751eb175f1e3fef745(),
			// Property: MdnResponse
			"mdn_response": schemaAttribute3865d88206ea0194f76b2b93(),
			// Property: MdnSigningAlgorithm
			"mdn_signing_algorithm": schemaAttributebd97810883db720b68dd64b1(),
			// Property: MessageSubject
			"message_subject": schemaAttribute77d8bf0a34d592563f7de8ec(),
			// Property: PartnerProfileId
			"partner_profile_id": schemaAttribute013a78830d188e93d6719a3d(),
			// Property: PreserveContentType
			"preserve_content_type": schemaAttribute0110e43d05afe42636c01b9f(),
			// Property: SigningAlgorithm
			"signing_algorithm": schemaAttribute185000b0dc44c4b2488c99c9(),
		}, /*END SCHEMA*/
		Description: "Configuration for an AS2 connector.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute3865d88206ea0194f76b2b93() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "MDN Response setting for this AS2 connector configuration.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute43c0d4ee075f9d2ae0785684() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: PortNumber
			"port_number": schemaAttribute1b3bdff5b72b8a35ccdd50d3(),
			// Property: ResourceConfigurationArn
			"resource_configuration_arn": schemaAttribute27486c4779fd780958061426(),
		}, /*END SCHEMA*/
		Computed: true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute4ef5dac8330b4f06ac810a34() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "ARN or name of the secret in AWS Secrets Manager which contains the credentials for Basic authentication. If empty, Basic authentication is disabled for the AS2 connector",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute5005333c1391c22c0c705a83() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Compression setting for this AS2 connector configuration.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute56515eecfef7770f29055e81() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Encryption algorithm for this AS2 connector configuration.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute5e31105ccc9144bc75c66506() schema.Attribute {
	return (schema.SetNestedAttribute{ /*START ATTRIBUTE*/
		NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Key
				"key": schemaAttribute8c686a4dc3477f68e7e00090(),
				// Property: Value
				"value": schemaAttributea1a408e089084f646f722f86(),
			}, /*END SCHEMA*/
		}, /*END NESTED OBJECT*/
		Description: "Key-value pairs that can be used to group and search for connectors. Tags are metadata attached to connectors for any purpose.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute634c907fa6e6f6a38311dfcf() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: VpcLattice
			"vpc_lattice": schemaAttribute43c0d4ee075f9d2ae0785684(),
		}, /*END SCHEMA*/
		Description: "Egress configuration for the connector.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute63e6154f1deea5ff35d2bdf4() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Specifies the access role for the connector.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute77d8bf0a34d592563f7de8ec() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The message subject for this AS2 connector configuration.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute8c686a4dc3477f68e7e00090() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "The name assigned to the tag that you create.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute94109cfff5bbdb1b8c4f1de2() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "ARN or name of the secret in AWS Secrets Manager which contains the SFTP user's private keys or passwords.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute94aa5266d8cbcb4023416774() schema.Attribute {
	return (schema.SetAttribute{ /*START ATTRIBUTE*/
		ElementType: types.StringType,
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttribute95a2b0812ab402ea4be600ed() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: ServerIds
			"server_ids": schemaAttribute94aa5266d8cbcb4023416774(),
			// Property: Url
			"url": schemaAttributefb923d67665243c7a01792c6(),
		}, /*END SCHEMA*/
		Description: "Configuration for an AS2 connector with ASYNC MDN Response",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributea1a408e089084f646f722f86() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Contains one or more values that you assigned to the key name you create.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributeaf061243321e728cc3b4a007() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Detailed error message when Connector in ERRORED status",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributeb531329cc2bcaf0b3dd9dd88() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "Specifies the logging role for the connector.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributebd97810883db720b68dd64b1() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "MDN Signing algorithm for this AS2 connector configuration.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributed0451e2bbc9e388f79bc1fec() schema.Attribute {
	return (schema.ListAttribute{ /*START ATTRIBUTE*/
		ElementType: types.StringType,
		Description: "List of public host keys, for the external server to which you are connecting.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributed20b0d751eb175f1e3fef745() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "A unique identifier for the local profile.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributed2bad03cb8888d8dde8769d2() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "URL for Connector",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributed51f6c9be3789716c34a4567() schema.Attribute {
	return (schema.Int64Attribute{ /*START ATTRIBUTE*/
		Description: "Specifies the number of active connections that your connector can establish with the remote server at the same time.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributee45fef3c35e78250b316ae22() schema.Attribute {
	return (schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
		Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
			// Property: MaxConcurrentConnections
			"max_concurrent_connections": schemaAttributed51f6c9be3789716c34a4567(),
			// Property: TrustedHostKeys
			"trusted_host_keys": schemaAttributed0451e2bbc9e388f79bc1fec(),
			// Property: UserSecretId
			"user_secret_id": schemaAttribute94109cfff5bbdb1b8c4f1de2(),
		}, /*END SCHEMA*/
		Description: "Configuration for an SFTP connector.",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func schemaAttributefb923d67665243c7a01792c6() schema.Attribute {
	return (schema.StringAttribute{ /*START ATTRIBUTE*/
		Description: "URL of the server to receive the MDN response on",
		Computed:    true,
	} /*END ATTRIBUTE*/)
}

func init() {
	registry.AddDataSourceFactory("awscc_transfer_connector", connectorDataSource)
}

// connectorDataSource returns the Terraform awscc_transfer_connector data source.
// This Terraform data source corresponds to the CloudFormation AWS::Transfer::Connector resource.
func connectorDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AccessRole
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Specifies the access role for the connector.",
		//	  "maxLength": 2048,
		//	  "minLength": 20,
		//	  "pattern": "arn:.*role/.*",
		//	  "type": "string"
		//	}
		"access_role": schemaAttribute63e6154f1deea5ff35d2bdf4(),
		// Property: Arn
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Specifies the unique Amazon Resource Name (ARN) for the connector.",
		//	  "maxLength": 1600,
		//	  "minLength": 20,
		//	  "pattern": "arn:.*",
		//	  "type": "string"
		//	}
		"arn": schemaAttribute01a07b4d4c72a15fb793d329(),
		// Property: As2Config
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "description": "Configuration for an AS2 connector.",
		//	  "properties": {
		//	    "AsyncMdnConfig": {
		//	      "additionalProperties": false,
		//	      "description": "Configuration for an AS2 connector with ASYNC MDN Response",
		//	      "properties": {
		//	        "ServerIds": {
		//	          "insertionOrder": false,
		//	          "items": {
		//	            "description": "A unique identifier for the server.",
		//	            "maxLength": 19,
		//	            "minLength": 19,
		//	            "pattern": "^s-([0-9a-f]{17})$",
		//	            "type": "string"
		//	          },
		//	          "maxItems": 10,
		//	          "minItems": 1,
		//	          "type": "array",
		//	          "uniqueItems": true
		//	        },
		//	        "Url": {
		//	          "description": "URL of the server to receive the MDN response on",
		//	          "type": "string"
		//	        }
		//	      },
		//	      "required": [
		//	        "Url",
		//	        "ServerIds"
		//	      ],
		//	      "type": "object"
		//	    },
		//	    "BasicAuthSecretId": {
		//	      "description": "ARN or name of the secret in AWS Secrets Manager which contains the credentials for Basic authentication. If empty, Basic authentication is disabled for the AS2 connector",
		//	      "maxLength": 2048,
		//	      "minLength": 0,
		//	      "type": "string"
		//	    },
		//	    "Compression": {
		//	      "description": "Compression setting for this AS2 connector configuration.",
		//	      "enum": [
		//	        "ZLIB",
		//	        "DISABLED"
		//	      ],
		//	      "type": "string"
		//	    },
		//	    "EncryptionAlgorithm": {
		//	      "description": "Encryption algorithm for this AS2 connector configuration.",
		//	      "enum": [
		//	        "AES128_CBC",
		//	        "AES192_CBC",
		//	        "AES256_CBC",
		//	        "NONE",
		//	        "DES_EDE3_CBC"
		//	      ],
		//	      "type": "string"
		//	    },
		//	    "LocalProfileId": {
		//	      "description": "A unique identifier for the local profile.",
		//	      "maxLength": 19,
		//	      "minLength": 19,
		//	      "pattern": "^p-([0-9a-f]{17})$",
		//	      "type": "string"
		//	    },
		//	    "MdnResponse": {
		//	      "description": "MDN Response setting for this AS2 connector configuration.",
		//	      "enum": [
		//	        "SYNC",
		//	        "ASYNC",
		//	        "NONE"
		//	      ],
		//	      "type": "string"
		//	    },
		//	    "MdnSigningAlgorithm": {
		//	      "description": "MDN Signing algorithm for this AS2 connector configuration.",
		//	      "enum": [
		//	        "SHA256",
		//	        "SHA384",
		//	        "SHA512",
		//	        "SHA1",
		//	        "NONE",
		//	        "DEFAULT"
		//	      ],
		//	      "type": "string"
		//	    },
		//	    "MessageSubject": {
		//	      "description": "The message subject for this AS2 connector configuration.",
		//	      "maxLength": 1024,
		//	      "minLength": 1,
		//	      "pattern": "",
		//	      "type": "string"
		//	    },
		//	    "PartnerProfileId": {
		//	      "description": "A unique identifier for the partner profile.",
		//	      "maxLength": 19,
		//	      "minLength": 19,
		//	      "pattern": "^p-([0-9a-f]{17})$",
		//	      "type": "string"
		//	    },
		//	    "PreserveContentType": {
		//	      "description": "Specifies whether to use the AWS S3 object content-type as the content-type for the AS2 message.",
		//	      "enum": [
		//	        "ENABLED",
		//	        "DISABLED"
		//	      ],
		//	      "type": "string"
		//	    },
		//	    "SigningAlgorithm": {
		//	      "description": "Signing algorithm for this AS2 connector configuration.",
		//	      "enum": [
		//	        "SHA256",
		//	        "SHA384",
		//	        "SHA512",
		//	        "SHA1",
		//	        "NONE"
		//	      ],
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"as_2_config": schemaAttribute30e8a5bc594a2e903c973cb6(),
		// Property: ConnectorId
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "A unique identifier for the connector.",
		//	  "maxLength": 19,
		//	  "minLength": 19,
		//	  "pattern": "^c-([0-9a-f]{17})$",
		//	  "type": "string"
		//	}
		"connector_id": schemaAttribute1081705d64512489570f63c0(),
		// Property: EgressConfig
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "description": "Egress configuration for the connector.",
		//	  "properties": {
		//	    "VpcLattice": {
		//	      "additionalProperties": false,
		//	      "properties": {
		//	        "PortNumber": {
		//	          "description": "Port to connect to on the target VPC Lattice resource",
		//	          "maximum": 65535,
		//	          "minimum": 1,
		//	          "type": "integer"
		//	        },
		//	        "ResourceConfigurationArn": {
		//	          "description": "ARN of the VPC Lattice resource configuration",
		//	          "maxLength": 2048,
		//	          "minLength": 1,
		//	          "pattern": "^arn:[a-z0-9\\-]+:vpc-lattice:[a-zA-Z0-9\\-]+:\\d{12}:resourceconfiguration/rcfg-[0-9a-z]{17}$",
		//	          "type": "string"
		//	        }
		//	      },
		//	      "required": [
		//	        "ResourceConfigurationArn"
		//	      ],
		//	      "type": "object"
		//	    }
		//	  },
		//	  "required": [
		//	    "VpcLattice"
		//	  ],
		//	  "type": "object"
		//	}
		"egress_config": schemaAttribute634c907fa6e6f6a38311dfcf(),
		// Property: EgressType
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Specifies the egress type for the connector.",
		//	  "enum": [
		//	    "SERVICE_MANAGED",
		//	    "VPC_LATTICE"
		//	  ],
		//	  "type": "string"
		//	}
		"egress_type": schemaAttribute2619d290bc51f2147fcb24f9(),
		// Property: ErrorMessage
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Detailed error message when Connector in ERRORED status",
		//	  "maxLength": 2048,
		//	  "type": "string"
		//	}
		"error_message": schemaAttributeaf061243321e728cc3b4a007(),
		// Property: IpAddressType
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "IP address type for Connector",
		//	  "enum": [
		//	    "IPV4",
		//	    "DUALSTACK"
		//	  ],
		//	  "type": "string"
		//	}
		"ip_address_type": schemaAttribute1b29d4dbf4682e7a255a2343(),
		// Property: LoggingRole
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Specifies the logging role for the connector.",
		//	  "maxLength": 2048,
		//	  "minLength": 20,
		//	  "pattern": "arn:.*role/.*",
		//	  "type": "string"
		//	}
		"logging_role": schemaAttributeb531329cc2bcaf0b3dd9dd88(),
		// Property: SecurityPolicyName
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Security policy for SFTP Connector",
		//	  "maxLength": 50,
		//	  "pattern": "TransferSFTPConnectorSecurityPolicy-[A-Za-z0-9-]+",
		//	  "type": "string"
		//	}
		"security_policy_name": schemaAttribute2f5c9b132bee8150bfa1e8d5(),
		// Property: ServiceManagedEgressIpAddresses
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "The list of egress IP addresses of this connector. These IP addresses are assigned automatically when you create the connector.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "pattern": "^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$",
		//	    "type": "string"
		//	  },
		//	  "type": "array"
		//	}
		"service_managed_egress_ip_addresses": schemaAttribute06acf0b4e0df0d313e7a71e7(),
		// Property: SftpConfig
		// CloudFormation resource type schema:
		//
		//	{
		//	  "additionalProperties": false,
		//	  "description": "Configuration for an SFTP connector.",
		//	  "properties": {
		//	    "MaxConcurrentConnections": {
		//	      "default": 1,
		//	      "description": "Specifies the number of active connections that your connector can establish with the remote server at the same time.",
		//	      "maximum": 5,
		//	      "minimum": 1,
		//	      "type": "integer"
		//	    },
		//	    "TrustedHostKeys": {
		//	      "description": "List of public host keys, for the external server to which you are connecting.",
		//	      "insertionOrder": false,
		//	      "items": {
		//	        "description": "The public host key for the external server to which you are connecting.",
		//	        "maxLength": 2048,
		//	        "minLength": 1,
		//	        "type": "string"
		//	      },
		//	      "maxItems": 10,
		//	      "type": "array",
		//	      "uniqueItems": false
		//	    },
		//	    "UserSecretId": {
		//	      "description": "ARN or name of the secret in AWS Secrets Manager which contains the SFTP user's private keys or passwords.",
		//	      "maxLength": 2048,
		//	      "minLength": 1,
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"sftp_config": schemaAttributee45fef3c35e78250b316ae22(),
		// Property: Status
		// CloudFormation resource type schema:
		//
		//	{
		//	  "enum": [
		//	    "ACTIVE",
		//	    "PENDING",
		//	    "ERRORED"
		//	  ],
		//	  "type": "string"
		//	}
		"status": schemaAttribute142b2bfefcd2a991e5bca0b7(),
		// Property: Tags
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "Key-value pairs that can be used to group and search for connectors. Tags are metadata attached to connectors for any purpose.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "additionalProperties": false,
		//	    "description": "Creates a key-value pair for a specific resource.",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "The name assigned to the tag that you create.",
		//	        "maxLength": 128,
		//	        "minLength": 1,
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Contains one or more values that you assigned to the key name you create.",
		//	        "maxLength": 256,
		//	        "minLength": 0,
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key",
		//	      "Value"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "maxItems": 50,
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schemaAttribute5e31105ccc9144bc75c66506(),
		// Property: Url
		// CloudFormation resource type schema:
		//
		//	{
		//	  "description": "URL for Connector",
		//	  "maxLength": 255,
		//	  "type": "string"
		//	}
		"url": schemaAttributed2bad03cb8888d8dde8769d2(),
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for AWS::Transfer::Connector",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudFormationTypeName("AWS::Transfer::Connector").WithTerraformTypeName("awscc_transfer_connector")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"access_role":                         "AccessRole",
		"arn":                                 "Arn",
		"as_2_config":                         "As2Config",
		"async_mdn_config":                    "AsyncMdnConfig",
		"basic_auth_secret_id":                "BasicAuthSecretId",
		"compression":                         "Compression",
		"connector_id":                        "ConnectorId",
		"egress_config":                       "EgressConfig",
		"egress_type":                         "EgressType",
		"encryption_algorithm":                "EncryptionAlgorithm",
		"error_message":                       "ErrorMessage",
		"ip_address_type":                     "IpAddressType",
		"key":                                 "Key",
		"local_profile_id":                    "LocalProfileId",
		"logging_role":                        "LoggingRole",
		"max_concurrent_connections":          "MaxConcurrentConnections",
		"mdn_response":                        "MdnResponse",
		"mdn_signing_algorithm":               "MdnSigningAlgorithm",
		"message_subject":                     "MessageSubject",
		"partner_profile_id":                  "PartnerProfileId",
		"port_number":                         "PortNumber",
		"preserve_content_type":               "PreserveContentType",
		"resource_configuration_arn":          "ResourceConfigurationArn",
		"security_policy_name":                "SecurityPolicyName",
		"server_ids":                          "ServerIds",
		"service_managed_egress_ip_addresses": "ServiceManagedEgressIpAddresses",
		"sftp_config":                         "SftpConfig",
		"signing_algorithm":                   "SigningAlgorithm",
		"status":                              "Status",
		"tags":                                "Tags",
		"trusted_host_keys":                   "TrustedHostKeys",
		"url":                                 "Url",
		"user_secret_id":                      "UserSecretId",
		"value":                               "Value",
		"vpc_lattice":                         "VpcLattice",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
