# Copyright IBM Corp. 2021, 2026
# "SPDX-License-Identifier: MPL-2.0"

name: Check if tfplugindocs result matches /docs

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .github/workflows/tfplugindocs-check.yml
      - .golangci.yml
      - go.sum
      - GNUmakefile
      - internal/**
      - main.go
      - tools/**
      - docs/**
      - examples/**

permissions:
  contents: read # Needed for checkout

jobs:
  tfplugindocs_check:
    name: tfplugindocs check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: tools/go.mod
      - name: GOCACHE
        run: |
          echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        continue-on-error: true
        timeout-minutes: 2
        with:
          # TODO: Replace with supported mechanism when it is supported
          # https://github.com/actions/setup-go/issues/54
          path: ${{ env.GOCACHE }}
          key: ${{ runner.os }}-GOCACHE-${{ hashFiles('go.sum') }}-${{ hashFiles('internal/**') }}
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e
        with:
          terraform_wrapper: false

      - run: |
          make tools
          make docs-fmt
          make docs
          git add -N docs/
          git diff --exit-code
